import { CalendarOff, Eye, Plus, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { cancelEmployeeLeave, getEmployeeLeave, getEmployeeLeaves } from "../../../api/employeeLeaves";
import { CrmDialog } from "../../../components/crm/Dialog";
import { EmployeeSelector } from "../../../components/crm/EmployeeSelector";
import { StatusBadge } from "../../../components/crm/StatusBadge";
import type { Employee } from "../../../types/employee";
import type { EmployeeLeave, EmployeeLeaveStatus, EmployeeLeaveType, WorkforcePaginator } from "../../../types/workforce";
import { hasPermission } from "../../../utils/authStorage";
import { addDateOnlyDays, bogotaDateTimeLocalToTimestamp, formatCrmTimestamp } from "../../../utils/crmDateTime";
import { leaveStatusLabel, leaveTypeLabel } from "../../../utils/crmPresentation";
import { LeaveFormDialog } from "./LeaveFormDialog";
import "./AdminLeavesPage.css";

const emptyResult: WorkforcePaginator<EmployeeLeave> = { current_page: 1, data: [], last_page: 1, per_page: 20, total: 0 };
const initialEmployeeId = () => { const id = Number(new URLSearchParams(window.location.search).get("employee_id")); return Number.isInteger(id) && id > 0 ? id : null; };
const leaveTypes: EmployeeLeaveType[] = ["vacation", "permission", "sick_leave", "absence", "other"];

export const AdminLeavesPage = () => {
  const canCreate = hasPermission("employee_leaves.create"); const canUpdate = hasPermission("employee_leaves.update"); const canCancel = hasPermission("employee_leaves.cancel");
  const [employeeId, setEmployeeId] = useState<number | null>(initialEmployeeId);
  const [type, setType] = useState<EmployeeLeaveType | "">(""); const [status, setStatus] = useState<EmployeeLeaveStatus | "">("");
  const [dateFrom, setDateFrom] = useState(""); const [dateTo, setDateTo] = useState(""); const [page, setPage] = useState(1);
  const [result, setResult] = useState<WorkforcePaginator<EmployeeLeave>>(emptyResult); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const [formLeave, setFormLeave] = useState<EmployeeLeave | "new" | null>(null); const [detail, setDetail] = useState<EmployeeLeave | null>(null); const [detailLoading, setDetailLoading] = useState(false); const [cancelling, setCancelling] = useState<EmployeeLeave | null>(null); const [mutating, setMutating] = useState(false); const [refreshVersion, setRefreshVersion] = useState(0); const requestId = useRef(0); const detailRequest = useRef(0); const detailAbort = useRef<AbortController | null>(null);

  useEffect(() => {
    const controller = new AbortController(); const request = ++requestId.current; setLoading(true); setError("");
    const from = dateFrom ? bogotaDateTimeLocalToTimestamp(`${dateFrom}T00:00`) ?? undefined : undefined;
    const nextDay = dateTo ? addDateOnlyDays(dateTo, 1) : null;
    const to = nextDay ? bogotaDateTimeLocalToTimestamp(`${nextDay}T00:00`) ?? undefined : undefined;
    getEmployeeLeaves({ employee_id: employeeId ?? undefined, type: type || undefined, status: status || undefined, from, to, page, per_page: 20 }, controller.signal)
      .then((data) => { if (request !== requestId.current) return; if (!data.data.length && page > Math.max(1, data.last_page)) { setPage(Math.max(1, data.last_page)); return; } setResult(data); })
      .catch((cause) => { if (!(cause instanceof DOMException && cause.name === "AbortError") && request === requestId.current) setError(cause instanceof Error ? cause.message : "No se pudieron cargar las ausencias."); })
      .finally(() => { if (request === requestId.current) setLoading(false); });
    return () => { controller.abort(); requestId.current += 1; };
  }, [dateFrom, dateTo, employeeId, page, refreshVersion, status, type]);

  useEffect(() => () => detailAbort.current?.abort(), []);

  const selectEmployee = (employee: Employee | null) => { setEmployeeId(employee?.id ?? null); setPage(1); const url = new URL(window.location.href); if (employee) url.searchParams.set("employee_id", String(employee.id)); else url.searchParams.delete("employee_id"); window.history.replaceState({}, "", `${url.pathname}${url.search}`); };
  const openDetail = async (id: number) => { detailAbort.current?.abort(); const controller = new AbortController(); detailAbort.current = controller; const request = ++detailRequest.current; setDetail(null); setDetailLoading(true); setError(""); try { const row = await getEmployeeLeave(id, controller.signal); if (request === detailRequest.current) setDetail(row); } catch (cause) { if (!(cause instanceof DOMException && cause.name === "AbortError") && request === detailRequest.current) setError(cause instanceof Error ? cause.message : "No se pudo cargar el detalle."); } finally { if (request === detailRequest.current) { setDetailLoading(false); detailAbort.current = null; } } };
  const closeDetail = () => { detailAbort.current?.abort(); detailAbort.current = null; detailRequest.current += 1; setDetailLoading(false); setDetail(null); };
  const saved = (feedback: string) => { setFormLeave(null); setMessage(feedback); setRefreshVersion((current) => current + 1); };
  const confirmCancel = async () => { if (!cancelling) return; setMutating(true); setError(""); try { await cancelEmployeeLeave(cancelling.id); setCancelling(null); setDetail(null); setMessage("Ausencia cancelada correctamente."); setRefreshVersion((current) => current + 1); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo cancelar la ausencia."); } finally { setMutating(false); } };

  return <section className="admin-leaves" aria-labelledby="leaves-heading">
    <header className="leaves-header"><div><span>Personal</span><h2 id="leaves-heading">Ausencias</h2><p>Registra vacaciones, permisos, incapacidades y otras ausencias aprobadas.</p></div>{canCreate ? <button className="is-primary" type="button" onClick={() => setFormLeave("new")}><Plus size={17} aria-hidden="true" />Registrar ausencia</button> : null}</header>
    <div className="leaves-filters"><EmployeeSelector value={employeeId} onChange={selectEmployee} allowAll /><label><span>Tipo</span><select value={type} onChange={(event) => { setType(event.target.value as EmployeeLeaveType | ""); setPage(1); }}><option value="">Todos</option>{leaveTypes.map((value) => <option key={value} value={value}>{leaveTypeLabel(value)}</option>)}</select></label><label><span>Estado</span><select value={status} onChange={(event) => { setStatus(event.target.value as EmployeeLeaveStatus | ""); setPage(1); }}><option value="">Todos</option><option value="approved">Aprobada</option><option value="cancelled">Cancelada</option></select></label><label><span>Desde</span><input type="date" value={dateFrom} onChange={(event) => { const next = event.target.value; setDateFrom(next); if (dateTo && next && dateTo < next) setDateTo(""); setPage(1); }} /></label><label><span>Hasta</span><input type="date" min={dateFrom} value={dateTo} onChange={(event) => { setDateTo(event.target.value); setPage(1); }} /></label></div>
    {message ? <p className="leaves-feedback" role="status">{message}</p> : null}{error ? <div className="leaves-feedback is-error" role="alert"><span>{error}</span><button type="button" onClick={() => setRefreshVersion((current) => current + 1)}>Reintentar</button></div> : null}{loading && result.data.length ? <span className="sr-only" role="status">Actualizando ausencias...</span> : null}
    {loading && !result.data.length ? <div className="leaves-state" role="status">Cargando ausencias...</div> : !loading && !result.data.length ? <div className="leaves-state"><CalendarOff size={25} aria-hidden="true" /><strong>No hay ausencias con estos filtros.</strong>{canCreate ? <button type="button" onClick={() => setFormLeave("new")}>Registrar ausencia</button> : null}</div> : <>
      <div className={`leaves-content ${loading ? "is-updating" : ""}`}><div className="leaves-table-wrap"><table><thead><tr><th>Empleado</th><th>Tipo</th><th>Inicio</th><th>Fin</th><th>Estado</th><th><span className="sr-only">Acciones</span></th></tr></thead><tbody>{result.data.map((leave) => <tr key={leave.id}><td>{leave.employee?.name ?? `Empleado #${leave.employee_id}`}</td><td>{leaveTypeLabel(leave.type)}</td><td>{formatCrmTimestamp(leave.starts_at)}</td><td>{formatCrmTimestamp(leave.ends_at)}</td><td><StatusBadge label={leaveStatusLabel(leave.status)} tone={leave.status === "approved" ? "success" : "neutral"} /></td><td><LeaveActions leave={leave} canUpdate={canUpdate} canCancel={canCancel} onDetail={() => void openDetail(leave.id)} onEdit={() => setFormLeave(leave)} onCancel={() => setCancelling(leave)} /></td></tr>)}</tbody></table></div>
      <div className="leaves-cards">{result.data.map((leave) => <article key={leave.id}><header><div><strong>{leave.employee?.name ?? `Empleado #${leave.employee_id}`}</strong><span>{leaveTypeLabel(leave.type)}</span></div><StatusBadge label={leaveStatusLabel(leave.status)} tone={leave.status === "approved" ? "success" : "neutral"} /></header><dl><div><dt>Inicio</dt><dd>{formatCrmTimestamp(leave.starts_at)}</dd></div><div><dt>Fin</dt><dd>{formatCrmTimestamp(leave.ends_at)}</dd></div></dl><LeaveActions leave={leave} canUpdate={canUpdate} canCancel={canCancel} onDetail={() => void openDetail(leave.id)} onEdit={() => setFormLeave(leave)} onCancel={() => setCancelling(leave)} /></article>)}</div></div>
      {result.last_page > 1 ? <nav className="leaves-pagination" aria-label="Paginación de ausencias"><button type="button" disabled={loading || result.current_page <= 1} onClick={() => setPage((current) => current - 1)}>Anterior</button><span>Página {result.current_page} de {result.last_page}</span><button type="button" disabled={loading || result.current_page >= result.last_page} onClick={() => setPage((current) => current + 1)}>Siguiente</button></nav> : null}</>}
    {formLeave ? <LeaveFormDialog leave={formLeave === "new" ? null : formLeave} initialEmployeeId={employeeId} onClose={() => setFormLeave(null)} onSaved={saved} /> : null}
    <LeaveDetailDialog leave={detail} loading={detailLoading} canUpdate={canUpdate} canCancel={canCancel} onClose={closeDetail} onEdit={() => { if (detail) setFormLeave(detail); closeDetail(); }} onCancel={() => { setCancelling(detail); closeDetail(); }} />
    <CrmDialog open={Boolean(cancelling)} titleId="leave-cancel-title" onClose={() => setCancelling(null)} busy={mutating} className="leave-confirm"><article><header><div><span>Confirmación</span><h2 id="leave-cancel-title" data-dialog-initial tabIndex={-1}>Cancelar ausencia</h2></div><button type="button" aria-label="Cerrar" disabled={mutating} onClick={() => setCancelling(null)}><X size={20} aria-hidden="true" /></button></header><p>La ausencia permanecerá en el historial con estado Cancelada.</p><footer><button type="button" disabled={mutating} onClick={() => setCancelling(null)}>Volver</button><button className="is-danger" type="button" disabled={mutating} onClick={() => void confirmCancel()}>{mutating ? "Cancelando..." : "Cancelar ausencia"}</button></footer></article></CrmDialog>
  </section>;
};

const LeaveActions = ({ leave, canUpdate, canCancel, onDetail, onEdit, onCancel }: { leave: EmployeeLeave; canUpdate: boolean; canCancel: boolean; onDetail: () => void; onEdit: () => void; onCancel: () => void }) => <div className="leave-actions"><button type="button" onClick={onDetail}><Eye size={15} aria-hidden="true" />Ver</button>{leave.status === "approved" && canUpdate ? <button type="button" onClick={onEdit}>Editar</button> : null}{leave.status === "approved" && canCancel ? <button className="is-danger" type="button" onClick={onCancel}>Cancelar</button> : null}</div>;

const LeaveDetailDialog = ({ leave, loading, canUpdate, canCancel, onClose, onEdit, onCancel }: { leave: EmployeeLeave | null; loading: boolean; canUpdate: boolean; canCancel: boolean; onClose: () => void; onEdit: () => void; onCancel: () => void }) => <CrmDialog open={Boolean(leave) || loading} titleId="leave-detail-title" onClose={onClose} className="leave-detail"><article><header><div><span>Detalle administrativo</span><h2 id="leave-detail-title" data-dialog-initial tabIndex={-1}>{leave ? leaveTypeLabel(leave.type) : "Cargando ausencia..."}</h2></div><button type="button" aria-label="Cerrar" onClick={onClose}><X size={20} aria-hidden="true" /></button></header>{!leave ? <p role="status">Cargando detalle...</p> : <div className="leave-detail__body"><div className="leave-detail__title"><strong>{leave.employee?.name ?? `Empleado #${leave.employee_id}`}</strong><StatusBadge label={leaveStatusLabel(leave.status)} tone={leave.status === "approved" ? "success" : "neutral"} /></div><dl><div><dt>Inicio</dt><dd>{formatCrmTimestamp(leave.starts_at)}</dd></div><div><dt>Fin</dt><dd>{formatCrmTimestamp(leave.ends_at)}</dd></div><div><dt>Aprobada por</dt><dd>{leave.approver?.name ?? "—"}</dd></div><div><dt>Cancelada por</dt><dd>{leave.canceller?.name ?? "—"}</dd></div></dl><section><h3>Motivo</h3><p>{leave.reason ?? "Sin motivo registrado."}</p></section><section><h3>Notas administrativas</h3><p>{leave.notes ?? "Sin notas."}</p></section></div>}{leave?.status === "approved" ? <footer>{canUpdate ? <button type="button" onClick={onEdit}>Editar</button> : null}{canCancel ? <button className="is-danger" type="button" onClick={onCancel}>Cancelar ausencia</button> : null}</footer> : null}</article></CrmDialog>;
