import { useEffect, useRef, useState, type FormEvent } from "react";
import { KeyRound, UserRound } from "lucide-react";
import { AuthApiError, getMe, updateMe, updateMyPassword } from "../../../api/auth";
import type { AuthUser } from "../../../types/auth";
import { getAuthUser, saveAuthUser } from "../../../utils/authStorage";
import "./AdminSettingsPage.css";

export const ProfilePage = () => {
  const [user, setUser] = useState<AuthUser | null>(getAuthUser());
  const [profile, setProfile] = useState({ name: user?.name ?? "", email: user?.email ?? "" });
  const [password, setPassword] = useState({ current_password: "", password: "", password_confirmation: "" });
  const [loading, setLoading] = useState(!user); const [profileSaving, setProfileSaving] = useState(false); const [passwordSaving, setPasswordSaving] = useState(false);
  const [profileMessage, setProfileMessage] = useState(""); const [passwordMessage, setPasswordMessage] = useState(""); const [profileError, setProfileError] = useState(""); const [passwordError, setPasswordError] = useState("");
  const profileLock = useRef(false); const passwordLock = useRef(false);
  useEffect(() => { let active = true; if (user) return; void getMe().then(({ user: value }) => { if (active) { setUser(value); setProfile({ name: value.name, email: value.email }); saveAuthUser(value); } }).catch((cause) => { if (active) setProfileError(cause instanceof Error ? cause.message : "No se pudo cargar el perfil."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [user]);
  const saveProfile = async (event: FormEvent) => { event.preventDefault(); if (profileLock.current) return; profileLock.current = true; setProfileSaving(true); setProfileError(""); setProfileMessage(""); try { const result = await updateMe({ name: profile.name.trim(), email: profile.email.trim() }); const next = { ...user!, ...result, permissions: result.permissions ?? user?.permissions ?? [] }; saveAuthUser(next); setUser(next); setProfile({ name: next.name, email: next.email }); setProfileMessage("Perfil actualizado correctamente."); } catch (cause) { setProfileError(cause instanceof Error ? cause.message : "No se pudo actualizar el perfil."); } finally { profileLock.current = false; setProfileSaving(false); } };
  const savePassword = async (event: FormEvent) => { event.preventDefault(); if (passwordLock.current) return; setPasswordError(""); setPasswordMessage(""); if (password.password !== password.password_confirmation) { setPasswordError("La confirmación de la nueva contraseña no coincide."); return; } passwordLock.current = true; setPasswordSaving(true); try { const result = await updateMyPassword(password); setPassword({ current_password: "", password: "", password_confirmation: "" }); setPasswordMessage(result.message ?? "Contraseña actualizada correctamente."); } catch (cause) { setPasswordError(cause instanceof AuthApiError ? cause.message : "No se pudo cambiar la contraseña."); } finally { passwordLock.current = false; setPasswordSaving(false); } };
  if (loading) return <section className="profile-page"><p className="settings-state" role="status">Cargando perfil...</p></section>;
  return <section className="profile-page"><header className="settings-hero"><div><span>Cuenta personal</span><h2>Mi perfil</h2><p>Actualiza tus datos de acceso sin modificar tu rol ni permisos.</p></div></header><div className="profile-grid">
    <form className="profile-card" onSubmit={saveProfile}><header><UserRound aria-hidden="true" /><div><h3>Información personal</h3><p>Estos datos identifican tu cuenta en el CRM.</p></div></header><label><span>Nombre</span><input required value={profile.name} disabled={profileSaving} onChange={(event) => setProfile((current) => ({ ...current, name: event.target.value }))} /></label><label><span>Email</span><input required type="email" value={profile.email} disabled={profileSaving} onChange={(event) => setProfile((current) => ({ ...current, email: event.target.value }))} /></label><div className="profile-readonly"><span>Rol</span><strong>{user?.role === "admin" ? "Administrador" : "Usuario"}</strong></div><div className="settings-feedback" aria-live="polite">{profileMessage ? <p className="is-success">{profileMessage}</p> : null}{profileError ? <p role="alert">{profileError}</p> : null}</div><button type="submit" disabled={profileSaving || !profile.name.trim() || !profile.email.trim()}>{profileSaving ? "Guardando..." : "Guardar perfil"}</button></form>
    <form className="profile-card" onSubmit={savePassword}><header><KeyRound aria-hidden="true" /><div><h3>Cambiar contraseña</h3><p>La sesión se mantendrá activa después del cambio.</p></div></header><label><span>Contraseña actual</span><input required type="password" autoComplete="current-password" value={password.current_password} disabled={passwordSaving} onChange={(event) => setPassword((current) => ({ ...current, current_password: event.target.value }))} /></label><label><span>Nueva contraseña</span><input required type="password" autoComplete="new-password" value={password.password} disabled={passwordSaving} onChange={(event) => setPassword((current) => ({ ...current, password: event.target.value }))} /></label><label><span>Confirmar nueva contraseña</span><input required type="password" autoComplete="new-password" value={password.password_confirmation} disabled={passwordSaving} onChange={(event) => setPassword((current) => ({ ...current, password_confirmation: event.target.value }))} /></label><div className="settings-feedback" aria-live="polite">{passwordMessage ? <p className="is-success">{passwordMessage}</p> : null}{passwordError ? <p role="alert">{passwordError}</p> : null}</div><button type="submit" disabled={passwordSaving}>{passwordSaving ? "Cambiando..." : "Cambiar contraseña"}</button></form>
  </div></section>;
};
