import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import {
  createService,
  createServiceCategory,
  deactivateService,
  deactivateServiceCategory,
  getService,
  getServiceCategories,
  getServices,
  updateService,
  updateServiceCategory,
} from "../../../api/services";
import type { Service, ServiceCategory, ServiceCategoryPayload, ServicePayload } from "../../../types/service";
import { formatCurrency } from "../../../utils/formatCurrency";
import { hasPermission } from "../../../utils/authStorage";
import { useDialogFocus } from "../orders/useDialogFocus";
import { formatServiceDuration } from "../orders/ServicePicker";
import "./AdminServicesPage.css";

type StatusFilter = "all" | "active" | "inactive";
const emptyService = { service_category_id: "", name: "", description: "", price: "", cost: "", estimated_duration_minutes: "60", is_active: true, sort_order: "0" };
const emptyCategory = { name: "", description: "", is_active: true, sort_order: "0" };

export const AdminServicesPage = () => {
  const canCreate = hasPermission("services.create");
  const canUpdate = hasPermission("services.update");
  const canDeactivate = hasPermission("services.delete");
  const canManageCategories = canCreate || canUpdate || canDeactivate;
  const [tab, setTab] = useState<"services" | "categories">("services");
  const [services, setServices] = useState<Service[]>([]);
  const [categories, setCategories] = useState<ServiceCategory[]>([]);
  const [page, setPage] = useState(1); const [lastPage, setLastPage] = useState(1);
  const [searchInput, setSearchInput] = useState(""); const [search, setSearch] = useState("");
  const [categoryId, setCategoryId] = useState(""); const [status, setStatus] = useState<StatusFilter>("all");
  const [loading, setLoading] = useState(true); const [categoriesLoading, setCategoriesLoading] = useState(true);
  const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const [selected, setSelected] = useState<Service | null>(null); const [detailLoading, setDetailLoading] = useState(false);
  const [serviceForm, setServiceForm] = useState<typeof emptyService | null>(null); const [editingService, setEditingService] = useState<Service | null>(null);
  const [categoryForm, setCategoryForm] = useState<typeof emptyCategory | null>(null); const [editingCategory, setEditingCategory] = useState<ServiceCategory | null>(null);
  const [saving, setSaving] = useState(false); const [confirmTarget, setConfirmTarget] = useState<Service | ServiceCategory | null>(null);
  const requestId = useRef(0); const categoryRequestId = useRef(0); const mutationLock = useRef(false);
  const dialogOpen = Boolean(serviceForm || categoryForm || selected || confirmTarget);
  const closeDialog = () => { if (mutationLock.current) return; setServiceForm(null); setCategoryForm(null); setSelected(null); setConfirmTarget(null); };
  const dialogRef = useDialogFocus<HTMLDivElement>({ open: dialogOpen, onEscape: closeDialog, canClose: !saving });

  const loadCategories = useCallback(async () => {
    const current = ++categoryRequestId.current; setCategoriesLoading(true);
    try { const result = await getServiceCategories({ page: 1, per_page: 100, sort: "sort_order", direction: "asc" }); if (current === categoryRequestId.current) setCategories(result.data); }
    catch (cause) { if (current === categoryRequestId.current) setError(cause instanceof Error ? cause.message : "No se pudieron cargar las categorías."); }
    finally { if (current === categoryRequestId.current) setCategoriesLoading(false); }
  }, []);
  const loadServices = useCallback(async () => {
    const current = ++requestId.current; setLoading(true); setError("");
    try { const result = await getServices({ search: search || undefined, service_category_id: categoryId ? Number(categoryId) : undefined, is_active: status === "all" ? undefined : status === "active", page, per_page: 25, sort: "sort_order", direction: "asc" }); if (current === requestId.current) { setServices(result.data); setLastPage(result.last_page); } }
    catch (cause) { if (current === requestId.current) setError(cause instanceof Error ? cause.message : "No se pudieron cargar los servicios."); }
    finally { if (current === requestId.current) setLoading(false); }
  }, [categoryId, page, search, status]);
  useEffect(() => { void loadCategories(); }, [loadCategories]);
  useEffect(() => { void loadServices(); return () => { requestId.current += 1; }; }, [loadServices]);
  useEffect(() => { if (!dialogOpen) return; const overflow = document.body.style.overflow; document.body.style.overflow = "hidden"; return () => { document.body.style.overflow = overflow; }; }, [dialogOpen]);

  const openCreateService = () => { setEditingService(null); setServiceForm({ ...emptyService }); setMessage(""); };
  const openEditService = (service: Service) => { setEditingService(service); setServiceForm({ service_category_id: String(service.service_category_id), name: service.name, description: service.description ?? "", price: String(service.price), cost: service.cost === null ? "" : String(service.cost), estimated_duration_minutes: String(service.estimated_duration_minutes), is_active: service.is_active, sort_order: String(service.sort_order) }); };
  const openCreateCategory = () => { setEditingCategory(null); setCategoryForm({ ...emptyCategory }); setMessage(""); };
  const openEditCategory = (category: ServiceCategory) => { setEditingCategory(category); setCategoryForm({ name: category.name, description: category.description ?? "", is_active: category.is_active, sort_order: String(category.sort_order) }); };
  const openDetail = async (id: number) => { setDetailLoading(true); setError(""); try { setSelected(await getService(id)); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo cargar el servicio."); } finally { setDetailLoading(false); } };
  const clean = (value: string) => value.trim() || null;
  const submitService = async (event: FormEvent) => { event.preventDefault(); if (!serviceForm || mutationLock.current) return; mutationLock.current = true; setSaving(true); setError(""); const payload: ServicePayload = { service_category_id: Number(serviceForm.service_category_id), name: serviceForm.name.trim(), description: clean(serviceForm.description), price: Number(serviceForm.price), cost: serviceForm.cost === "" ? null : Number(serviceForm.cost), estimated_duration_minutes: Number(serviceForm.estimated_duration_minutes), is_active: serviceForm.is_active, sort_order: Number(serviceForm.sort_order) }; try { await (editingService ? updateService(editingService.id, payload) : createService(payload)); setServiceForm(null); setMessage(editingService ? "Servicio actualizado." : "Servicio creado."); await loadServices(); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo guardar el servicio."); } finally { mutationLock.current = false; setSaving(false); } };
  const submitCategory = async (event: FormEvent) => { event.preventDefault(); if (!categoryForm || mutationLock.current) return; mutationLock.current = true; setSaving(true); setError(""); const payload: ServiceCategoryPayload = { name: categoryForm.name.trim(), description: clean(categoryForm.description), is_active: categoryForm.is_active, sort_order: Number(categoryForm.sort_order) }; try { await (editingCategory ? updateServiceCategory(editingCategory.id, payload) : createServiceCategory(payload)); setCategoryForm(null); setMessage(editingCategory ? "Categoría actualizada." : "Categoría creada."); await loadCategories(); await loadServices(); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo guardar la categoría."); } finally { mutationLock.current = false; setSaving(false); } };
  const confirmDeactivate = async () => { if (!confirmTarget || mutationLock.current) return; mutationLock.current = true; setSaving(true); setError(""); try { if ("service_category_id" in confirmTarget) await deactivateService(confirmTarget.id); else await deactivateServiceCategory(confirmTarget.id); setConfirmTarget(null); setMessage("Registro desactivado; el histórico se conserva."); await loadCategories(); await loadServices(); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo desactivar el registro."); } finally { mutationLock.current = false; setSaving(false); } };
  const submitSearch = (event: FormEvent) => { event.preventDefault(); setPage(1); setSearch(searchInput.trim()); };

  return <section className="admin-services">
    <header className="admin-services__header"><div><span>Catálogo operativo</span><h2>Servicios</h2><p>Administra mano de obra y conceptos no inventariables para ventas y cotizaciones.</p></div>{tab === "services" && canCreate ? <button className="is-primary" type="button" onClick={openCreateService}>Nuevo servicio</button> : tab === "categories" && canCreate ? <button className="is-primary" type="button" onClick={openCreateCategory}>Nueva categoría</button> : null}</header>
    <div className="services-tabs" role="tablist" aria-label="Secciones de Servicios"><button type="button" role="tab" aria-selected={tab === "services"} onClick={() => setTab("services")}>Servicios</button>{canManageCategories ? <button type="button" role="tab" aria-selected={tab === "categories"} onClick={() => setTab("categories")}>Categorías</button> : null}</div>
    {message ? <p className="services-message is-success" role="status">{message}</p> : null}{error ? <p className="services-message is-error" role="alert">{error} <button type="button" onClick={() => void (tab === "services" ? loadServices() : loadCategories())}>Reintentar</button></p> : null}
    {tab === "services" ? <>
      <form className="services-filters" role="search" onSubmit={submitSearch}><label><span>Buscar</span><input value={searchInput} onChange={(event) => setSearchInput(event.target.value)} placeholder="Nombre o descripción" /></label><button type="submit" disabled={loading}>{loading ? "Buscando..." : "Buscar"}</button><label><span>Categoría</span><select value={categoryId} disabled={categoriesLoading} onChange={(event) => { setCategoryId(event.target.value); setPage(1); }}><option value="">Todas</option>{categories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label><label><span>Estado</span><select value={status} onChange={(event) => { setStatus(event.target.value as StatusFilter); setPage(1); }}><option value="all">Todos</option><option value="active">Activos</option><option value="inactive">Inactivos</option></select></label></form>
      {loading ? <div className="services-state" role="status">Cargando servicios...</div> : !services.length ? <div className="services-state">No encontramos servicios con estos filtros.</div> : <><div className="services-table"><div className="services-table__head"><span>Servicio</span><span>Categoría</span><span>Precio</span><span>Duración</span><span>Estado</span><span>Acciones</span></div>{services.map((service) => <article key={service.id}><div><strong>{service.name}</strong><small>{service.description || "Sin descripción"}</small></div><span>{service.category?.name ?? "Sin categoría"}</span><strong>{formatCurrency(service.price)}</strong><span>{formatServiceDuration(service.estimated_duration_minutes)}</span><span className={service.is_active ? "service-status is-active" : "service-status"}>{service.is_active ? "Activo" : "Inactivo"}</span><div className="services-actions"><button type="button" onClick={() => void openDetail(service.id)}>Ver</button>{canUpdate ? <button type="button" onClick={() => openEditService(service)}>Editar</button> : null}{canDeactivate && service.is_active ? <button className="is-danger" type="button" onClick={() => setConfirmTarget(service)}>Desactivar</button> : null}</div></article>)}</div><div className="services-cards">{services.map((service) => <article key={service.id}><header><div><strong>{service.name}</strong><small>{service.category?.name ?? "Sin categoría"}</small></div><span className={service.is_active ? "service-status is-active" : "service-status"}>{service.is_active ? "Activo" : "Inactivo"}</span></header><dl><div><dt>Precio</dt><dd>{formatCurrency(service.price)}</dd></div><div><dt>Duración</dt><dd>{formatServiceDuration(service.estimated_duration_minutes)}</dd></div></dl><div className="services-actions"><button type="button" onClick={() => void openDetail(service.id)}>Ver</button>{canUpdate ? <button type="button" onClick={() => openEditService(service)}>Editar</button> : null}{canDeactivate && service.is_active ? <button className="is-danger" type="button" onClick={() => setConfirmTarget(service)}>Desactivar</button> : null}</div></article>)}</div></>}
      <nav className="services-pagination" aria-label="Paginación de servicios"><button type="button" disabled={loading || page <= 1} onClick={() => setPage((value) => value - 1)}>Anterior</button><span>Página {page} de {lastPage}</span><button type="button" disabled={loading || page >= lastPage} onClick={() => setPage((value) => value + 1)}>Siguiente</button></nav>
    </> : <div className="service-categories-panel">{categoriesLoading ? <p role="status">Cargando categorías...</p> : !categories.length ? <p>No hay categorías de servicios.</p> : categories.map((category) => <article key={category.id}><div><strong>{category.name}</strong><p>{category.description || "Sin descripción"}</p><small>Orden {category.sort_order} · {category.is_active ? "Activa" : "Inactiva"}</small></div><div className="services-actions">{canUpdate ? <button type="button" onClick={() => openEditCategory(category)}>Editar</button> : null}{canDeactivate && category.is_active ? <button className="is-danger" type="button" onClick={() => setConfirmTarget(category)}>Desactivar</button> : null}</div></article>)}</div>}
    {dialogOpen ? <div ref={dialogRef} className="service-dialog" role="dialog" aria-modal="true" aria-labelledby="service-dialog-title" tabIndex={-1}><button className="service-dialog__backdrop" type="button" aria-label="Cerrar" tabIndex={-1} disabled={saving} onClick={closeDialog} /><div className="service-dialog__panel">
      {serviceForm ? <form onSubmit={submitService}><header><div><span>Servicio</span><h2 id="service-dialog-title" data-dialog-initial tabIndex={-1}>{editingService ? "Editar servicio" : "Nuevo servicio"}</h2></div><button type="button" disabled={saving} onClick={closeDialog}>Cerrar</button></header><div className="service-dialog__body"><label><span>Categoría</span><select required value={serviceForm.service_category_id} onChange={(event) => setServiceForm({ ...serviceForm, service_category_id: event.target.value })}><option value="">Seleccionar</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}{category.is_active ? "" : " (inactiva)"}</option>)}</select></label><label><span>Nombre</span><input required maxLength={160} value={serviceForm.name} onChange={(event) => setServiceForm({ ...serviceForm, name: event.target.value })} /></label><label className="is-wide"><span>Descripción</span><textarea value={serviceForm.description} onChange={(event) => setServiceForm({ ...serviceForm, description: event.target.value })} /></label><label><span>Precio COP</span><input required type="number" min="0" step="1" value={serviceForm.price} onChange={(event) => setServiceForm({ ...serviceForm, price: event.target.value })} /></label><label><span>Costo directo opcional</span><input type="number" min="0" step="1" value={serviceForm.cost} onChange={(event) => setServiceForm({ ...serviceForm, cost: event.target.value })} /></label><label><span>Duración en minutos</span><input required type="number" min="5" max="1440" value={serviceForm.estimated_duration_minutes} onChange={(event) => setServiceForm({ ...serviceForm, estimated_duration_minutes: event.target.value })} /></label><label><span>Orden</span><input required type="number" min="0" value={serviceForm.sort_order} onChange={(event) => setServiceForm({ ...serviceForm, sort_order: event.target.value })} /></label><label className="service-check"><input type="checkbox" checked={serviceForm.is_active} onChange={(event) => setServiceForm({ ...serviceForm, is_active: event.target.checked })} /><span>Servicio activo</span></label></div><footer><button type="button" disabled={saving} onClick={closeDialog}>Cancelar</button><button className="is-primary" type="submit" disabled={saving}>{saving ? "Guardando..." : "Guardar servicio"}</button></footer></form> : null}
      {categoryForm ? <form onSubmit={submitCategory}><header><div><span>Categoría</span><h2 id="service-dialog-title" data-dialog-initial tabIndex={-1}>{editingCategory ? "Editar categoría" : "Nueva categoría"}</h2></div><button type="button" disabled={saving} onClick={closeDialog}>Cerrar</button></header><div className="service-dialog__body"><label><span>Nombre</span><input required maxLength={160} value={categoryForm.name} onChange={(event) => setCategoryForm({ ...categoryForm, name: event.target.value })} /></label><label className="is-wide"><span>Descripción</span><textarea value={categoryForm.description} onChange={(event) => setCategoryForm({ ...categoryForm, description: event.target.value })} /></label><label><span>Orden</span><input required type="number" min="0" value={categoryForm.sort_order} onChange={(event) => setCategoryForm({ ...categoryForm, sort_order: event.target.value })} /></label><label className="service-check"><input type="checkbox" checked={categoryForm.is_active} onChange={(event) => setCategoryForm({ ...categoryForm, is_active: event.target.checked })} /><span>Categoría activa</span></label>{!categoryForm.is_active ? <p className="is-wide">Sus servicios dejarán de estar disponibles para nuevas ventas y cotizaciones; no se desactivan individualmente.</p> : null}</div><footer><button type="button" disabled={saving} onClick={closeDialog}>Cancelar</button><button className="is-primary" type="submit" disabled={saving}>{saving ? "Guardando..." : "Guardar categoría"}</button></footer></form> : null}
      {selected || detailLoading ? <article><header><div><span>Detalle</span><h2 id="service-dialog-title" data-dialog-initial tabIndex={-1}>{selected?.name ?? "Cargando servicio..."}</h2></div><button type="button" onClick={closeDialog}>Cerrar</button></header>{selected ? <div className="service-detail"><span className={selected.is_active ? "service-status is-active" : "service-status"}>{selected.is_active ? "Activo" : "Inactivo"}</span><p>{selected.description || "Sin descripción."}</p><dl><div><dt>Categoría</dt><dd>{selected.category?.name ?? "Sin categoría"}</dd></div><div><dt>Precio</dt><dd>{formatCurrency(selected.price)}</dd></div>{canUpdate ? <div><dt>Costo</dt><dd>{selected.cost === null ? "Sin costo registrado" : formatCurrency(selected.cost)}</dd></div> : null}<div><dt>Duración</dt><dd>{formatServiceDuration(selected.estimated_duration_minutes)}</dd></div></dl></div> : <p className="service-detail" role="status">Cargando...</p>}</article> : null}
      {confirmTarget ? <article><header><div><span>Confirmación</span><h2 id="service-dialog-title" data-dialog-initial tabIndex={-1}>Desactivar {"service_category_id" in confirmTarget ? "servicio" : "categoría"}</h2></div></header><div className="service-detail"><p><strong>{confirmTarget.name}</strong> dejará de estar disponible para nuevas operaciones, pero el histórico se conservará.</p>{!("service_category_id" in confirmTarget) ? <p>Los servicios de esta categoría dejarán de ser seleccionables; no serán desactivados individualmente.</p> : null}</div><footer><button type="button" disabled={saving} onClick={closeDialog}>Cancelar</button><button className="is-danger" type="button" disabled={saving} onClick={() => void confirmDeactivate()}>{saving ? "Desactivando..." : "Desactivar"}</button></footer></article> : null}
    </div></div> : null}
  </section>;
};
