import type { ReactNode } from "react";
import type { AnyReport, CustomerReportRow, CustomersReport, InventoryMovementRow, InventoryMovementsReport, InventoryReport, InventoryRow, PaymentReportRow, PaymentsReport, ProductReportRow, ProductsReport, QuotationReportRow, QuotationsReport, ReceivableRow, ReceivablesReport, ReportFinancials, ReportKind, SalesPoint, SalesReport, SalesRow } from "../../../types/report";
import { formatCurrency } from "../../../utils/formatCurrency";
import { formatDateOnly, formatDateTime, inventoryLabels, methodLabels, movementLabels, paymentLabels, percent, quotationLabels } from "./reportUtils";

type Cell = string | number | ReactNode;
type TableRow = { key: string | number; cells: Cell[] };
const Metrics = ({ items }: { items: Array<[string, Cell, string?]> }) => <dl className="report-metrics">{items.map(([label, value, help]) => <div key={label}><dt>{label}</dt><dd>{value}</dd>{help ? <small>{help}</small> : null}</div>)}</dl>;
const Status = ({ value, label }: { value: string; label?: string }) => <span className={`report-status report-status--${value}`}>{label ?? value}</span>;
const Table = ({ columns, rows, empty }: { columns: string[]; rows: TableRow[]; empty: string }) => rows.length ? <><div className="report-table-wrap"><table className="report-table"><thead><tr>{columns.map((column) => <th key={column} scope="col">{column}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.key}>{row.cells.map((cell, index) => <td key={`${row.key}-${columns[index]}`}>{cell}</td>)}</tr>)}</tbody></table></div><ul className="report-mobile-list">{rows.map((row) => <li key={row.key}>{row.cells.map((cell, index) => <div key={`${row.key}-m-${columns[index]}`}><span>{columns[index]}</span><strong>{cell}</strong></div>)}</li>)}</ul></> : <p className="report-empty">{empty}</p>;

const Financials = ({ value }: { value: ReportFinancials }) => <section className="report-financials" aria-labelledby="financials-title"><div><span>Acceso financiero</span><h3 id="financials-title">Rentabilidad del periodo</h3></div><Metrics items={[["Revenue",formatCurrency(value.revenue)],["Revenue con costo",formatCurrency(value.known_cost_revenue)],["COGS conocido",formatCurrency(value.cogs)],["Utilidad bruta conocida",formatCurrency(value.gross_profit_on_known_cost)],["Margen",percent(value.gross_margin_percent)],["Cobertura",percent(value.cost_coverage_percent)]]}/>{value.cost_coverage_percent < 100 ? <p>La rentabilidad se calcula únicamente sobre ventas con costo histórico disponible.</p> : null}</section>;

const shortCurrency = (value: number) => value >= 1_000_000 ? `$${new Intl.NumberFormat("es-CO", { maximumFractionDigits: 1 }).format(value / 1_000_000)} M` : value >= 1_000 ? `$${new Intl.NumberFormat("es-CO", { maximumFractionDigits: 0 }).format(value / 1_000)} mil` : formatCurrency(value);

const SalesChart = ({ points }: { points: SalesPoint[] }) => {
  const width=800,height=260,p={t:18,r:16,b:38,l:68},w=width-p.l-p.r,h=height-p.t-p.b,max=Math.max(0,...points.map(x=>Number(x.total)||0)),scale=max||1;
  const x=(i:number)=>p.l+(points.length>1?i/(points.length-1):0)*w,y=(v:number)=>p.t+h-v/scale*h;
  const path=points.map((point,i)=>`${i?"L":"M"} ${x(i).toFixed(2)} ${y(point.total).toFixed(2)}`).join(" ");
  const labels=points.length<=6?points.map((_,i)=>i):Array.from(new Set([0,Math.floor((points.length-1)*.25),Math.floor((points.length-1)*.5),Math.floor((points.length-1)*.75),points.length-1]));
  return <div className="report-chart"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-labelledby="report-chart-title report-chart-desc"><title id="report-chart-title">Ventas diarias del periodo</title><desc id="report-chart-desc">{points.length} días; total máximo diario {formatCurrency(max)}.</desc>{[1,.5,0].map(t=><g key={t}><line x1={p.l} x2={width-p.r} y1={p.t+h*(1-t)} y2={p.t+h*(1-t)}/><text x={p.l-10} y={p.t+h*(1-t)+4} textAnchor="end">{shortCurrency(scale*t)}</text></g>)}{path?<path d={path}/>:null}{labels.map(i=><text key={i} x={x(i)} y={height-10} textAnchor={i===0?"start":i===points.length-1?"end":"middle"}>{formatDateOnly(points[i]?.date)}</text>)}</svg></div>;
};

const branchLabel=(branch:{name:string;code:string}|null|undefined)=>branch?`${branch.name} · ${branch.code}`:"Sin sede";
const salesRows=(rows:SalesRow[]):TableRow[]=>rows.map(r=>({key:r.id,cells:[r.order_number,branchLabel(r.branch),formatDateTime(r.confirmed_at),r.customer_name,r.vehicle_summary??"—",r.origin.toUpperCase(),r.items_count,<Status value={r.payment_status} label={paymentLabels[r.payment_status]??r.payment_status}/>,formatCurrency(r.total),r.operator_name??"—"]}));
const productRows=(rows:ProductReportRow[],sku:boolean):TableRow[]=>rows.map((r,i)=>({key:`${r.product_id??"x"}-${r.product_variant_id??"x"}-${i}`,cells:[r.product_name,r.product_sku??"—",...(sku?[r.variant_name??"—",r.variant_sku??"—"]:[]),r.quantity,r.orders_count,formatCurrency(r.revenue),formatCurrency(r.discount_total),...(r.financials?[formatCurrency(r.financials.cogs),formatCurrency(r.financials.gross_profit_on_known_cost),percent(r.financials.gross_margin_percent)]:[])]}));
const paymentRows=(rows:PaymentReportRow[]):TableRow[]=>rows.map(r=>({key:r.id,cells:[formatDateTime(r.paid_at),r.branch_name?`${r.branch_name} · ${r.branch_code??""}`:"Sin sede",r.order_number,formatCurrency(r.amount),methodLabels[r.method]??r.method,<Status value={r.status} label={r.status==="refunded"?"Reembolsado":paymentLabels[r.status]??r.status}/>,r.reference??"—",r.operator_name??"—"]}));
const receivableRows=(rows:ReceivableRow[]):TableRow[]=>rows.map(r=>({key:r.order_id,cells:[r.order_number,branchLabel(r.branch),r.customer_name,formatCurrency(r.total),formatCurrency(r.paid),<strong className="report-emphasis">{formatCurrency(r.outstanding)}</strong>,<Status value={r.payment_status} label={paymentLabels[r.payment_status]??r.payment_status}/>,formatDateTime(r.confirmed_at),`${r.days_outstanding} días`,r.operator_name??"—"]}));
const inventoryRows=(rows:InventoryRow[]):TableRow[]=>rows.map(r=>({key:`${r.branch.id}-${r.type}-${r.product_variant_id??r.product_id}`,cells:[branchLabel(r.branch),r.type==="variant"?"Variante":"Producto",r.name,r.variant_name??"—",r.sku??"—",r.stock,r.minimum_stock,<Status value={r.status} label={inventoryLabels[r.status]??r.status}/>,...(r.current_cost!==undefined?[formatCurrency(r.current_cost)]:[])]}));
const movementRows=(rows:InventoryMovementRow[]):TableRow[]=>rows.map(r=>({key:r.id,cells:[formatDateTime(r.created_at),r.branch_name?`${r.branch_name} · ${r.branch_code??""}`:"Sin sede histórica",r.product_name,r.variant_name??"—",r.sku??"—",movementLabels[r.type]??r.type,<strong className={r.quantity_delta>=0?"is-positive":"is-negative"}>{r.quantity_delta>0?"+":""}{r.quantity_delta}</strong>,r.stock_before,r.stock_after,r.operator_name??"—",r.reference_type&&r.reference_id?`${r.reference_type} #${r.reference_id}`:"—"]}));
const quotationRows=(rows:QuotationReportRow[]):TableRow[]=>rows.map(r=>({key:r.id,cells:[r.quotation_number,branchLabel(r.branch),formatDateTime(r.created_at),r.customer_name,r.vehicle_summary??"—",formatDateOnly(r.valid_until),<Status value={r.status} label={quotationLabels[r.status]??r.status}/>,formatCurrency(r.total),r.operator_name??"—",r.order_number??"—"]}));
const customerRows=(rows:CustomerReportRow[]):TableRow[]=>rows.map(r=>({key:r.customer_id,cells:[r.name,<Status value={r.is_active?"active":"inactive"} label={r.is_active?"Activo":"Inactivo"}/>,formatDateTime(r.created_at),r.orders_count,formatCurrency(r.total_spent),formatCurrency(r.average_ticket),formatDateTime(r.last_purchase_at),r.vehicles_count]}));

export const ReportResults = ({ kind, report }: { kind: ReportKind; report: AnyReport }) => {
  if(kind==="sales"){const r=report as SalesReport;return <><Metrics items={[["Ventas",r.summary.orders_count],["Total vendido",formatCurrency(r.summary.sales_total)],["Ticket promedio",formatCurrency(r.summary.average_ticket)],["Descuentos",formatCurrency(r.summary.discount_total)]]}/><section className="report-breakdown"><h3>Origen de las ventas</h3><div><article><span>CRM</span><strong>{formatCurrency(r.breakdown.crm.total)}</strong><small>{r.breakdown.crm.orders_count} ventas</small></article><article><span>Ecommerce</span><strong>{formatCurrency(r.breakdown.ecommerce.total)}</strong><small>{r.breakdown.ecommerce.orders_count} ventas</small></article></div></section><section className="report-panel"><h3>Ventas por día</h3><SalesChart points={r.by_day}/></section>{r.financials?<Financials value={r.financials}/>:null}<Table columns={["Venta","Sede","Fecha","Cliente","Vehículo","Origen","Items","Pago","Total","Operador"]} rows={salesRows(r.rows.data)} empty="No hay ventas para este periodo."/></>}
  if(kind==="products"){const r=report as ProductsReport,sku=r.group_by==="sku",financialRows=r.rows.data.some(x=>x.financials);return <><Metrics items={[["Unidades vendidas",r.summary.units_sold],["Revenue",formatCurrency(r.summary.revenue)],["Descuentos",formatCurrency(r.summary.discount_total)],["Órdenes distintas",r.summary.distinct_orders]]}/>{r.financials?<Financials value={r.financials}/>:null}<Table columns={["Producto","SKU",...(sku?["Variante","SKU variante"]:[]),"Cantidad","Órdenes","Revenue","Descuento",...(financialRows?["COGS","Utilidad","Margen"]:[])]} rows={productRows(r.rows.data,sku)} empty="No hay productos vendidos para este periodo."/></>}
  if(kind==="payments"){const r=report as PaymentsReport;return <><Metrics items={[["Pagos completados",r.summary.completed_count],["Monto recibido",formatCurrency(r.summary.completed_amount)]]}/><section className="report-breakdown"><h3>Pagos completados por método</h3><div>{Object.entries(r.summary.by_method).map(([method,value])=><article key={method}><span>{methodLabels[method]??method}</span><strong>{formatCurrency(value.amount)}</strong><small>{value.count} pagos</small></article>)}</div><p>Los reembolsos no se descuentan de este resumen en esta fase.</p></section><Table columns={["Fecha","Sede","Orden","Monto","Método","Estado","Referencia","Operador"]} rows={paymentRows(r.rows.data)} empty="No hay pagos con estos filtros."/></>}
  if(kind==="receivables"){const r=report as ReceivablesReport;return <><Metrics items={[["Total por cobrar",formatCurrency(r.summary.outstanding_total)],["Órdenes con saldo",r.summary.orders_with_balance]]}/><Table columns={["Orden","Sede","Cliente","Total","Pagado","Pendiente","Estado","Fecha venta","Antigüedad","Operador"]} rows={receivableRows(r.rows.data)} empty="No hay órdenes pendientes por cobrar."/></>}
  if(kind==="inventory"){const r=report as InventoryReport,financial=r.rows.data.some(x=>x.current_cost!==undefined);return <><Metrics items={[["Posiciones",r.summary.units_count],["Cantidad total",r.summary.total_quantity],["Stock bajo",r.summary.low_count],["Agotado",r.summary.out_count]]}/><Table columns={["Sede","Tipo","Producto","Variante","SKU","Stock","Mínimo","Estado",...(financial?["Costo actual"]:[])]} rows={inventoryRows(r.rows.data)} empty="No encontramos unidades con estos filtros."/></>}
  if(kind==="inventory-movements"){const r=report as InventoryMovementsReport;return <><Metrics items={[["Movimientos",r.summary.movements_count],["Unidades de entrada",r.summary.units_in],["Unidades de salida",r.summary.units_out]]}/><section className="report-breakdown"><h3>Movimientos por tipo</h3><div>{Object.entries(r.summary.by_type).map(([type,count])=><article key={type}><span>{movementLabels[type]??type}</span><strong>{count}</strong></article>)}</div></section>{r.historical_reconciliation===false?<p className="report-note">Este reporte muestra movimientos registrados y no constituye una conciliación histórica completa del inventario.</p>:null}<Table columns={["Fecha","Sede","Producto","Variante","SKU","Tipo","Cambio","Anterior","Posterior","Operador","Referencia"]} rows={movementRows(r.rows.data)} empty="No hay movimientos para este periodo."/></>}
  if(kind==="quotations"){const r=report as QuotationsReport,s=r.summary;return <><Metrics items={[["Creadas en el periodo",s.created_in_period],["Convertidas en el periodo",s.converted_in_period],["Resueltas en el periodo",s.resolved_in_period],["Conversión",percent(s.conversion_rate_resolved),"Sobre cotizaciones resueltas"]]}/><section className="report-detail-grid"><span>Enviadas <strong>{s.sent_in_period}</strong></span><span>Rechazadas <strong>{s.rejected_in_period}</strong></span><span>Vencidas <strong>{s.expired_in_period}</strong></span><span>Valor cotizado <strong>{formatCurrency(s.total_quoted_created_in_period)}</strong></span><span>Valor convertido <strong>{formatCurrency(s.total_converted_in_period)}</strong></span></section><Table columns={["Cotización","Sede","Creación","Cliente","Vehículo","Vigencia","Estado","Total","Operador","Venta"]} rows={quotationRows(r.rows.data)} empty="No hay cotizaciones para este periodo."/></>}
  const r=report as CustomersReport;return <><Metrics items={[["Clientes registrados",r.summary.registered_total,"Registro global actual"],["Activos",r.summary.active_total,"Registro global actual"],["Nuevos en el periodo",r.summary.new_in_period],[r.context.mode==="branch"?"Atendidos en la sede":"Compradores en el periodo",r.summary.buyers_in_period]]}/>{r.context.mode==="branch"?<p className="report-note">Los clientes son globales. La sede limita únicamente su actividad comercial durante el periodo.</p>:null}<Table columns={["Cliente","Estado","Fecha alta","Compras","Total comprado","Ticket promedio","Última compra","Vehículos"]} rows={customerRows(r.rows.data)} empty="No encontramos clientes con estos filtros."/></>;
};
