import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import { convertQuotation, createQuotation, getQuotation, getQuotations, updateQuotation, updateQuotationStatus } from "../../../api/quotations";
import type { Quotation, QuotationPayload, QuotationStatus } from "../../../types/quotation";
import { hasPermission } from "../../../utils/authStorage";
import { QuotationDetail } from "./QuotationDetail"; import { QuotationForm } from "./QuotationForm"; import { QuotationList } from "./QuotationList"; import { quotationStatusLabels } from "./quotationUtils";
import "./AdminQuotationsPage.css";

export const AdminQuotationsPage=()=>{const canView=hasPermission("quotations.view");const [rows,setRows]=useState<Quotation[]>([]);const [page,setPage]=useState(1);const [lastPage,setLastPage]=useState(1);const [searchInput,setSearchInput]=useState("");const [search,setSearch]=useState("");const [status,setStatus]=useState<"all"|QuotationStatus>("all");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [selected,setSelected]=useState<Quotation|null>(null);const [detailLoading,setDetailLoading]=useState(false);const [formOpen,setFormOpen]=useState(false);const [editing,setEditing]=useState<Quotation|null>(null);const detailRequest=useRef(0);
const load=useCallback(async()=>{if(!canView)return;setLoading(true);setError("");try{const result=await getQuotations({search:search||undefined,status:status==="all"?undefined:status,page,per_page:15});setRows(result.data);setLastPage(result.last_page);}catch(cause){setError(cause instanceof Error?cause.message:"No se pudieron cargar las cotizaciones.");}finally{setLoading(false);}},[canView,page,search,status]);useEffect(()=>{void load();},[load]);
const open=async(id:number)=>{const request=++detailRequest.current;setDetailLoading(true);setError("");try{const result=await getQuotation(id);if(request===detailRequest.current)setSelected(result);}catch(cause){if(request===detailRequest.current)setError(cause instanceof Error?cause.message:"No se pudo cargar la cotización.");}finally{if(request===detailRequest.current)setDetailLoading(false);}};
const refreshDetail=async(id:number)=>{await open(id);await load();};const saved=(quotation:Quotation)=>{setFormOpen(false);setEditing(null);setSelected(quotation);void refreshDetail(quotation.id);};const submitSearch=(e:FormEvent)=>{e.preventDefault();setPage(1);setSearch(searchInput.trim());};
if(!canView)return <section className="admin-quotations"><div className="quotations-state"><h2>Acceso restringido</h2><p>No tienes permiso para consultar cotizaciones.</p><a href="/crm">Volver al CRM</a></div></section>;
return <section className="admin-quotations"><header className="admin-quotations__header"><div><span>Operación comercial</span><h2>Cotizaciones</h2><p>Crea propuestas, conserva precios históricos y conviértelas en ventas cuando el cliente decida.</p></div>{hasPermission("quotations.create")?<button className="is-primary" type="button" onClick={()=>{setEditing(null);setFormOpen(true);}}>Nueva cotización</button>:null}</header><form className="quotations-filters" onSubmit={submitSearch} role="search"><label><span>Buscar</span><input value={searchInput} onChange={e=>setSearchInput(e.target.value)} placeholder="Número, cliente, teléfono o email"/></label><button type="submit">{loading?"Buscando...":"Buscar"}</button><label><span>Estado</span><select value={status} onChange={e=>{setStatus(e.target.value as "all"|QuotationStatus);setPage(1);}}><option value="all">Todos</option>{Object.entries(quotationStatusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></form>{error?<p className="quotation-error" role="alert">{error}</p>:null}{!loading&&!rows.length&&!search&&!status?<p className="quotations-state">Todavía no hay cotizaciones.</p>:<QuotationList quotations={rows} loading={loading} onOpen={id=>void open(id)}/>}<nav className="quotations-pagination" aria-label="Paginación"><button type="button" disabled={page<=1||loading} onClick={()=>setPage(x=>x-1)}>Anterior</button><span>Página {page} de {lastPage}</span><button type="button" disabled={page>=lastPage||loading} onClick={()=>setPage(x=>x+1)}>Siguiente</button></nav><QuotationForm open={formOpen} quotation={editing} onClose={()=>{setFormOpen(false);setEditing(null);}} onSubmit={payload=>editing?updateQuotation(editing.id,payload):createQuotation(payload)} onSaved={saved}/><QuotationDetail quotation={selected} loading={detailLoading} onClose={()=>{detailRequest.current++;setSelected(null);}} onEdit={()=>{setEditing(selected);setFormOpen(true);setSelected(null);}} onStatus={async(statusValue,reason)=>{if(!selected)return;await updateQuotationStatus(selected.id,{status:statusValue,reason});await refreshDetail(selected.id);}} onConvert={async()=>{if(!selected)return;await convertQuotation(selected.id);await refreshDetail(selected.id);}}/></section>};
