import { useRef, useState } from "react";
import type { Quotation, QuotationStatus } from "../../../types/quotation";
import { formatCurrency } from "../../../utils/formatCurrency";
import { hasPermission } from "../../../utils/authStorage";
import { useDialogFocus } from "../orders/useDialogFocus";
import { formatDate, quotationStatusLabels, vehicleSummary } from "./quotationUtils";

type Props = { quotation: Quotation | null; loading: boolean; onClose: () => void; onEdit: () => void; onStatus: (status: QuotationStatus, reason?: string) => Promise<void>; onConvert: () => Promise<void> };
export const QuotationDetail = ({ quotation, loading, onClose, onEdit, onStatus, onConvert }: Props) => {
  const [confirm, setConfirm] = useState<"reject"|"convert"|null>(null); const [reason,setReason]=useState(""); const [action,setAction]=useState(""); const [error,setError]=useState(""); const lock=useRef(false);
  const dialogRef=useDialogFocus<HTMLDivElement>({open:Boolean(quotation)||loading,onEscape:onClose,canClose:!action});
  if (!quotation && !loading) return null;
  const run=async(kind:"sent"|"rejected"|"converted")=>{if(lock.current)return;lock.current=true;setAction(kind);setError("");try{if(kind==="converted")await onConvert();else await onStatus(kind,kind==="rejected"?reason:undefined);setConfirm(null);setReason("");}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo completar la acción.");}finally{lock.current=false;setAction("");}};
  if (!quotation) return <div className="quotation-sheet" role="dialog" aria-modal="true"><div className="quotation-detail" role="status">Cargando cotización...</div></div>;
  const editable=["draft","sent"].includes(quotation.status); const history=quotation.status_history??quotation.statusHistory??[];
  return <div ref={dialogRef} className="quotation-sheet" role="dialog" aria-modal="true" aria-labelledby="quotation-detail-title" tabIndex={-1}><button className="quotation-sheet__backdrop" type="button" tabIndex={-1} aria-label="Cerrar detalle" onClick={onClose}/><article className="quotation-detail"><header><div><span>Cotización</span><h2 id="quotation-detail-title" data-dialog-initial tabIndex={-1}>{quotation.quotation_number}</h2><p>Creada {formatDate(quotation.created_at,true)}</p></div><button type="button" onClick={onClose}>Cerrar</button></header><div className="quotation-detail__body"><section className="quotation-detail__summary"><span className={`quotation-status quotation-status--${quotation.status}`}>{quotationStatusLabels[quotation.status]}</span><div><span>Válida hasta</span><strong>{formatDate(quotation.valid_until)}</strong></div><div><span>Total</span><strong>{formatCurrency(quotation.total)}</strong></div></section>
  <section><h3>Cliente</h3><strong>{quotation.customer_name||"Venta mostrador"}</strong><p>{[quotation.customer_phone,quotation.customer_email,quotation.customer_document,quotation.customer_city,quotation.customer_address].filter(Boolean).join(" · ")||"Sin datos de cliente"}</p>{quotation.customer_notes?<p>{quotation.customer_notes}</p>:null}</section><section><h3>Vehículo</h3><strong>{vehicleSummary(quotation)}</strong><p>{[quotation.vehicle_vin&&`VIN ${quotation.vehicle_vin}`,quotation.vehicle_color,quotation.vehicle_notes].filter(Boolean).join(" · ")||"Sin datos adicionales"}</p></section>
  <section><h3>Productos y servicios</h3><div className="quotation-detail__items">{(quotation.items??[]).map(item=>{const isService=item.item_type==="service";return <article key={item.id}><div><span className="commercial-line-type">{isService?"Servicio":"Producto"}</span><strong>{isService?item.service_name||"Servicio":item.product_name||"Producto histórico"}</strong>{isService?item.service_description?<small>{item.service_description}</small>:null:<><small>{[item.variant_name,item.variant_sku||item.product_sku].filter(Boolean).join(" · ")}</small><span>{Object.entries(item.variant_specs??{}).slice(0,4).map(([k,v])=>`${k}: ${String(v)}`).join(" · ")}</span></>}</div><div><span>{item.quantity} × {formatCurrency(item.unit_price)}</span>{item.discount_amount>0?<small>Descuento {formatCurrency(item.discount_amount)}</small>:null}<strong>{formatCurrency(item.total)}</strong></div></article>})}</div></section><section className="quotation-totals"><span>Subtotal <strong>{formatCurrency(quotation.subtotal)}</strong></span><span>Descuentos <strong>{formatCurrency(quotation.discount_total)}</strong></span><span>Total <strong>{formatCurrency(quotation.total)}</strong></span></section>{quotation.notes?<section><h3>Notas</h3><p>{quotation.notes}</p></section>:null}
  <section><h3>Historial</h3>{history.length?<ol className="quotation-history">{history.map(item=><li key={item.id}><strong>{item.from_status?`${quotationStatusLabels[item.from_status]} → `:""}{quotationStatusLabels[item.to_status]}</strong><span>{formatDate(item.created_at,true)}{item.changedBy?.name?` · ${item.changedBy.name}`:""}</span>{item.reason?<p>{item.reason}</p>:null}</li>)}</ol>:<p>Sin movimientos registrados.</p>}</section>{quotation.status==="converted"?<section className="quotation-order"><h3>Venta generada</h3><strong>{quotation.order?.order_number||`Orden #${quotation.order_id}`}</strong><a href="/crm/orders">Ver en Órdenes</a></section>:null}{error?<p className="quotation-error" role="alert">{error}</p>:null}{confirm?<section className="quotation-confirm" aria-labelledby="quotation-confirm-title"><h3 id="quotation-confirm-title">{confirm==="convert"?"¿Convertir en venta?":"¿Marcar como rechazada?"}</h3><p>{confirm==="convert"?"Se creará una venta confirmada y el inventario se validará en ese momento.":"Esta acción dejará la cotización en estado terminal."}</p>{confirm==="reject"?<label className="quotation-field"><span>Razón opcional</span><textarea value={reason} onChange={e=>setReason(e.target.value)}/></label>:null}<div><button type="button" onClick={()=>setConfirm(null)}>Volver</button><button type="button" className="is-primary" disabled={Boolean(action)} onClick={()=>void run(confirm==="convert"?"converted":"rejected")}>{action?"Procesando...":"Confirmar"}</button></div></section>:null}</div><footer>{editable&&hasPermission("quotations.update")?<button type="button" onClick={onEdit}>Editar</button>:null}{quotation.status==="draft"&&hasPermission("quotations.update")?<button type="button" disabled={Boolean(action)} onClick={()=>void run("sent")}>{action==="sent"?"Guardando...":"Marcar como enviada"}</button>:null}{quotation.status==="sent"&&hasPermission("quotations.update")?<button type="button" onClick={()=>setConfirm("reject")}>Marcar como rechazada</button>:null}{editable&&hasPermission("quotations.convert")?<button type="button" className="is-primary" onClick={()=>setConfirm("convert")}>Convertir en venta</button>:null}</footer></article></div>;
};
