import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { listAllBranches } from "../../../api/branches";
import { getAdminProducts } from "../../../api/products";
import { getCustomerVehicles } from "../../../api/customers";
import { getVehicleBrands, getVehicleModels, getVehicleVersions } from "../../../api/vehicles";
import type { Branch } from "../../../types/branch";
import type { Customer, CustomerVehicle } from "../../../types/customer";
import type {
  AdminProduct,
  AdminProductVariant,
  Product,
  ProductVariant,
} from "../../../types/product";
import type { Service } from "../../../types/service";
import type { Quotation, QuotationPayload } from "../../../types/quotation";
import type { VehicleBrand, VehicleModel, VehicleVersion } from "../../../types/vehicle";
import { formatCurrency } from "../../../utils/formatCurrency";
import { hasPermission } from "../../../utils/authStorage";
import { CustomerPicker } from "../orders/CustomerPicker";
import { CommercialItemPicker } from "../orders/CommercialItemPicker";
import { formatServiceDuration } from "../orders/ServicePicker";
import { useDialogFocus } from "../orders/useDialogFocus";

type Mode = "none" | "existing" | "adhoc";
type Line =
  | { type: "product"; key: string; product: AdminProduct | Product; variant: AdminProductVariant | ProductVariant | null; quantity: number; discount: number }
  | { type: "service"; key: string; service: Service; quantity: number; discount: number };
type Props = { open: boolean; quotation: Quotation | null; initialCustomer?: Customer | null; onClose: () => void; onSubmit: (payload: QuotationPayload) => Promise<Quotation>; onSaved: (quotation: Quotation) => void };
const emptyCustomer = { name: "", phone: "", email: "", document: "", city: "", address: "", notes: "" };
const emptyVehicle = { brand: "", model: "", version: "", year: "", plate: "", vin: "", color: "", notes: "" };

export const QuotationForm = ({ open, quotation, initialCustomer = null, onClose, onSubmit, onSaved }: Props) => {
  const [branches, setBranches] = useState<Branch[]>([]); const [branchId, setBranchId] = useState(""); const [branchesLoading, setBranchesLoading] = useState(false); const [branchError, setBranchError] = useState("");
  const [products, setProducts] = useState<AdminProduct[]>([]); const [brands, setBrands] = useState<VehicleBrand[]>([]); const [models, setModels] = useState<VehicleModel[]>([]); const [versions, setVersions] = useState<VehicleVersion[]>([]);
  const [lines, setLines] = useState<Line[]>([]); const [customerMode, setCustomerMode] = useState<Mode>("none"); const [vehicleMode, setVehicleMode] = useState<Mode>("none");
  const [selectedCustomer, setSelectedCustomer] = useState<Customer | null>(null); const [vehicles, setVehicles] = useState<CustomerVehicle[]>([]); const [selectedVehicle, setSelectedVehicle] = useState<CustomerVehicle | null>(null);
  const [customer, setCustomer] = useState(emptyCustomer); const [vehicle, setVehicle] = useState(emptyVehicle); const [validUntil, setValidUntil] = useState(""); const [notes, setNotes] = useState("");
  const [loadingVehicles, setLoadingVehicles] = useState(false); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false); const lock = useRef(false); const vehicleRequest = useRef(0); const branchSelectRef = useRef<HTMLSelectElement>(null);
  const dialogRef = useDialogFocus<HTMLDivElement>({ open, onEscape: onClose, canClose: !submitting });
  const visibleModels = models.filter((item) => String(item.vehicle_brand_id) === vehicle.brand && item.is_active); const visibleVersions = versions.filter((item) => String(item.vehicle_model_id) === vehicle.model && item.is_active);
  const preview = useMemo(() => lines.reduce((sum, line) => sum + (line.type === "product" ? line.variant?.price ?? line.product.price : line.service.price) * line.quantity - line.discount, 0), [lines]);
  const availableBranches = useMemo(() => branches.filter((branch) => branch.is_active || branch.id === quotation?.branch_id), [branches, quotation?.branch_id]);

  const loadVehicles = async (next: Customer) => { const id = ++vehicleRequest.current; setLoadingVehicles(true); setVehicles([]); try { const data = await getCustomerVehicles(next.id); if (id === vehicleRequest.current) { const activeVehicles = data.filter((item) => item.is_active); setVehicles(data); if (activeVehicles.length === 1) { setVehicleMode("existing"); setSelectedVehicle(activeVehicles[0]); } } } catch (cause) { if (id === vehicleRequest.current) setError(cause instanceof Error ? cause.message : "No se pudieron cargar los vehículos."); } finally { if (id === vehicleRequest.current) setLoadingVehicles(false); } };
  useEffect(() => { if (!open) return; const controller = new AbortController(); setBranchesLoading(true); setBranchError(""); listAllBranches(controller.signal).then(setBranches).catch((cause) => { if (!controller.signal.aborted) setBranchError(cause instanceof Error ? cause.message : "No se pudieron cargar las sedes."); }).finally(() => { if (!controller.signal.aborted) setBranchesLoading(false); }); return () => controller.abort(); }, [open]);
  useEffect(() => { if (!open) return; Promise.all([getAdminProducts(), getVehicleBrands(), getVehicleModels(), getVehicleVersions()]).then(([p,b,m,v]) => { setProducts(p); setBrands(b); setModels(m); setVersions(v); }).catch((cause) => setError(cause instanceof Error ? cause.message : "No se pudieron cargar los datos.")); }, [open]);
  useEffect(() => { if (!open) return; const q = quotation; const handedCustomer = q ? null : initialCustomer; const selected = q?.customer ?? handedCustomer; setError(""); setBranchId(q?.branch_id ? String(q.branch_id) : ""); setValidUntil(q?.valid_until?.slice(0,10) ?? ""); setNotes(q?.notes ?? ""); setCustomer(q ? { name:q.customer_name??"", phone:q.customer_phone??"", email:q.customer_email??"", document:q.customer_document??"", city:q.customer_city??"", address:q.customer_address??"", notes:q.customer_notes??"" } : emptyCustomer); setVehicle(q ? { brand:String(q.vehicle_brand_id??""), model:String(q.vehicle_model_id??""), version:String(q.vehicle_version_id??""), year:String(q.vehicle_year??""), plate:q.vehicle_plate??"", vin:q.vehicle_vin??"", color:q.vehicle_color??"", notes:q.vehicle_notes??"" } : emptyVehicle); setSelectedCustomer(selected); setSelectedVehicle(q?.customer_vehicle ?? q?.customerVehicle ?? null); setCustomerMode(selected ? "existing" : q?.customer_name ? "adhoc" : "none"); setVehicleMode(q?.customer_vehicle_id ? "existing" : (q?.vehicle_brand_id || q?.vehicle_plate || q?.vehicle_vin) ? "adhoc" : "none"); setLines((q?.items ?? []).flatMap((item): Line[] => item.item_type === "service" && item.service ? [{ type:"service", key:`service:${item.service_id}`, service:item.service, quantity:item.quantity, discount:item.discount_amount }] : item.product ? [{ type:"product", key:`${item.product_id}:${item.product_variant_id ?? "product"}`, product:item.product, variant:item.product_variant ?? null, quantity:item.quantity, discount:item.discount_amount }] : [])); if (selected) void loadVehicles(selected); }, [open, quotation, initialCustomer?.id]);
  useEffect(() => { if (!open) return; const previous = document.body.style.overflow; document.body.style.overflow = "hidden"; return () => { document.body.style.overflow = previous; }; }, [open]);

  const addLine = (product: AdminProduct, variant: AdminProductVariant | null) => { const key = `${product.id}:${variant?.id ?? "product"}`; setLines((current) => current.some((line) => line.key === key) ? current.map((line) => line.key === key && line.type === "product" ? { ...line, quantity: line.quantity + 1 } : line) : [...current, { type:"product", key, product, variant, quantity:1, discount:0 }]); };
  const addServiceLine = (service: Service) => { const key = `service:${service.id}`; setLines((current) => current.some((line) => line.key === key) ? current.map((line) => line.key === key && line.type === "service" ? { ...line, quantity: Math.min(999, line.quantity + 1) } : line) : [...current, { type:"service", key, service, quantity:1, discount:0 }]); };
  const clean = (value: string) => value.trim() || undefined;
  const submit = async (event: FormEvent) => { event.preventDefault(); if (lock.current) return; if (!branchId) { setBranchError("Selecciona una sede para continuar."); branchSelectRef.current?.focus(); return; } if (!lines.length) { setError("Agrega al menos un producto."); return; } if (customerMode === "existing" && !selectedCustomer) { setError("Selecciona un cliente."); return; } if (vehicleMode === "existing" && !selectedVehicle) { setError("Selecciona un vehículo."); return; }
    const payload: QuotationPayload = { branch_id:Number(branchId), ...(validUntil ? { valid_until: validUntil } : {}), ...(customerMode === "existing" && selectedCustomer ? { customer_id:selectedCustomer.id, customer_notes:clean(customer.notes) } : {}), ...(customerMode === "adhoc" ? { customer_name:clean(customer.name), customer_phone:clean(customer.phone), customer_email:clean(customer.email), customer_document:clean(customer.document), customer_city:clean(customer.city), customer_address:clean(customer.address), customer_notes:clean(customer.notes) } : {}), ...(vehicleMode === "existing" && selectedVehicle ? { customer_vehicle_id:selectedVehicle.id } : {}), ...(vehicleMode === "adhoc" ? { vehicle_brand_id:vehicle.brand ? Number(vehicle.brand) : null, vehicle_model_id:vehicle.model ? Number(vehicle.model) : null, vehicle_version_id:vehicle.version ? Number(vehicle.version) : null, vehicle_year:vehicle.year ? Number(vehicle.year) : undefined, vehicle_plate:clean(vehicle.plate), vehicle_vin:clean(vehicle.vin), vehicle_color:clean(vehicle.color), vehicle_notes:clean(vehicle.notes) } : {}), notes:clean(notes), items:lines.map((line) => line.type === "service" ? { item_type:"service" as const, service_id:line.service.id, quantity:Math.max(1, line.quantity), discount_amount:Math.max(0, line.discount) } : { product_id:line.product.id, product_variant_id:line.variant?.id ?? null, quantity:Math.max(1, line.quantity), discount_amount:Math.max(0, line.discount) }) };
    lock.current = true; setSubmitting(true); setError(""); try { onSaved(await onSubmit(payload)); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo guardar la cotización."); } finally { lock.current = false; setSubmitting(false); }
  };
  if (!open) return null;
  return <div ref={dialogRef} className="quotation-sheet" role="dialog" aria-modal="true" aria-labelledby="quotation-form-title" tabIndex={-1}><button type="button" className="quotation-sheet__backdrop" aria-label="Cerrar formulario" tabIndex={-1} onClick={onClose} /><form className="quotation-sheet__panel" onSubmit={submit}><header><div><span>Cotización CRM</span><h2 id="quotation-form-title" data-dialog-initial tabIndex={-1}>{quotation ? "Editar cotización" : "Nueva cotización"}</h2><p>El precio final será calculado por el backend. Una cotización no reserva ni consume inventario.</p></div><button type="button" disabled={submitting} onClick={onClose}>Cerrar</button></header><div className="quotation-sheet__body">
    <fieldset><legend>Sede</legend><label className="quotation-field" htmlFor="quotation-branch"><span>Sede *</span><select ref={branchSelectRef} id="quotation-branch" value={branchId} required disabled={submitting || branchesLoading} aria-invalid={Boolean(branchError)} aria-describedby={`quotation-branch-help${branchError ? " quotation-branch-error" : ""}`} onInvalid={() => setBranchError("Selecciona una sede para continuar.")} onBlur={() => { if (!branchId && !branchesLoading && !branchError) setBranchError("Selecciona una sede para continuar."); }} onChange={(event) => { setBranchId(event.target.value); setBranchError(""); }}><option value="">{branchesLoading ? "Cargando sedes..." : "Seleccionar sede"}</option>{availableBranches.map((branch)=><option key={branch.id} value={branch.id}>{branch.name} · {branch.code}{branch.is_active ? "" : " (inactiva)"}</option>)}</select><small id="quotation-branch-help">Selecciona la sede desde la que se gestionará esta cotización.</small>{branchError?<small id="quotation-branch-error" className="quotation-field__error" role="alert">{branchError}</small>:null}</label></fieldset>
    <fieldset><legend>1. Cliente</legend><div className="quotation-modes">{([...[{value:"none",label:"Sin cliente"}], ...(hasPermission("customers.view") ? [{value:"existing",label:"Cliente existente"}] : []), {value:"adhoc",label:"Cliente ad hoc"}] as {value:Mode;label:string}[]).map((option) => <label key={option.value}><input type="radio" name="quote-customer" checked={customerMode===option.value} onChange={() => { setCustomerMode(option.value); setSelectedCustomer(null); setSelectedVehicle(null); setVehicleMode("none"); setVehicles([]); }} /><span>{option.label}</span></label>)}</div>{customerMode === "existing" ? <><CustomerPicker selected={selectedCustomer} disabled={submitting} onClear={() => { setSelectedCustomer(null); setSelectedVehicle(null); setVehicleMode("none"); }} onSelect={(next) => { setSelectedCustomer(next); setSelectedVehicle(null); setVehicleMode("none"); void loadVehicles(next); }} />{selectedCustomer ? <label className="quotation-field"><span>Nota de esta cotización</span><textarea value={customer.notes} onChange={(e)=>setCustomer({...customer,notes:e.target.value})}/></label>:null}</> : customerMode === "adhoc" ? <div className="quotation-grid">{([['name','Nombre'],['phone','Teléfono'],['email','Email'],['document','Documento'],['city','Ciudad'],['address','Dirección']] as const).map(([key,label])=><label className="quotation-field" key={key}><span>{label}</span><input type={key==='email'?'email':'text'} value={customer[key]} onChange={(e)=>setCustomer({...customer,[key]:e.target.value})}/></label>)}<label className="quotation-field is-wide"><span>Notas</span><textarea value={customer.notes} onChange={(e)=>setCustomer({...customer,notes:e.target.value})}/></label></div>:<p>La cotización quedará sin cliente persistente.</p>}</fieldset>
    <fieldset><legend>2. Vehículo</legend><div className="quotation-modes">{([{value:"none",label:"Sin vehículo"}, ...(selectedCustomer?[{value:"existing",label:"Vehículo del cliente"}]:[]), {value:"adhoc",label:"Vehículo ad hoc"}] as {value:Mode;label:string}[]).map((option)=><label key={option.value}><input type="radio" name="quote-vehicle" checked={vehicleMode===option.value} onChange={()=>{setVehicleMode(option.value);setSelectedVehicle(null);}}/><span>{option.label}</span></label>)}</div>{vehicleMode === "existing" ? <div className="quotation-vehicles">{loadingVehicles?<p role="status">Cargando vehículos...</p>:!vehicles.length?<p>Este cliente todavía no tiene vehículos registrados.</p>:vehicles.map((item)=><button type="button" disabled={!item.is_active} className={selectedVehicle?.id===item.id?"is-selected":""} key={item.id} onClick={()=>setSelectedVehicle(item)}><strong>{item.nickname || item.plate || "Vehículo registrado"}</strong><small>{[item.vehicle_brand?.name ?? item.vehicleBrand?.name,item.vehicle_model?.name ?? item.vehicleModel?.name,item.year,item.plate].filter(Boolean).join(" · ")}</small></button>)}</div>:vehicleMode === "adhoc"?<div className="quotation-grid"><label className="quotation-field"><span>Marca</span><select value={vehicle.brand} onChange={(e)=>setVehicle({...vehicle,brand:e.target.value,model:"",version:""})}><option value="">Seleccionar</option>{brands.filter(x=>x.is_active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="quotation-field"><span>Modelo</span><select disabled={!vehicle.brand} value={vehicle.model} onChange={(e)=>setVehicle({...vehicle,model:e.target.value,version:""})}><option value="">Seleccionar</option>{visibleModels.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="quotation-field"><span>Versión</span><select disabled={!vehicle.model} value={vehicle.version} onChange={(e)=>setVehicle({...vehicle,version:e.target.value})}><option value="">Seleccionar</option>{visibleVersions.map(x=><option key={x.id} value={x.id}>{x.display_name}</option>)}</select></label>{([['year','Año'],['plate','Placa'],['vin','VIN'],['color','Color']] as const).map(([key,label])=><label className="quotation-field" key={key}><span>{label}</span><input type={key==='year'?'number':'text'} value={vehicle[key]} onChange={(e)=>setVehicle({...vehicle,[key]:e.target.value})}/></label>)}<label className="quotation-field is-wide"><span>Notas</span><textarea value={vehicle.notes} onChange={(e)=>setVehicle({...vehicle,notes:e.target.value})}/></label></div>:<p>Sin vehículo asociado.</p>}</fieldset>
    <fieldset><legend>3. Productos y servicios</legend><CommercialItemPicker<AdminProduct, AdminProductVariant> products={products} onAddProduct={addLine} onAddService={addServiceLine} stockMode="none" disabled={submitting} /><p className="quotation-hint">Una cotización no reserva ni consume inventario. Los servicios no manejan stock.</p><div className="quotation-lines">{lines.map((line)=>{const isProduct=line.type==="product";return <article key={line.key}><div><span className="commercial-line-type">{isProduct?"Producto":"Servicio"}</span><strong>{isProduct?line.product.name:line.service.name}</strong><small>{isProduct?`${line.variant?.display_name || "Producto simple"} · ${line.variant?.sku || line.product.sku || "Sin SKU"}`:`${line.service.category?.name??"Sin categoría"} · ${formatServiceDuration(line.service.estimated_duration_minutes)}`}</small></div><label>Cantidad<input type="number" min="1" max="999" value={line.quantity} onChange={(e)=>setLines(current=>current.map(x=>x.key===line.key?{...x,quantity:Math.min(999,Math.max(1,Number(e.target.value)||1))}:x))}/></label><label>Descuento COP<input type="number" min="0" value={line.discount} onChange={(e)=>setLines(current=>current.map(x=>x.key===line.key?{...x,discount:Math.max(0,Number(e.target.value)||0)}:x))}/></label><button type="button" onClick={()=>setLines(current=>current.filter(x=>x.key!==line.key))}>Eliminar</button></article>})}</div></fieldset>
    <fieldset><legend>4. Vigencia y notas</legend><div className="quotation-grid"><label className="quotation-field"><span>Válida hasta</span><input type="date" min={new Date().toLocaleDateString("en-CA")} value={validUntil} onChange={(e)=>setValidUntil(e.target.value)}/><small>Vacío: se aplicará la vigencia configurada en Ventas y cotizaciones.</small></label><label className="quotation-field is-wide"><span>Notas de la cotización</span><textarea value={notes} onChange={(e)=>setNotes(e.target.value)}/></label></div></fieldset>{error?<p className="quotation-error" role="alert">{error}</p>:null}</div><footer><div><span>Vista previa estimada</span><strong>{formatCurrency(Math.max(0,preview))}</strong><small>El backend confirmará los totales.</small></div><button type="submit" disabled={submitting||!lines.length}>{submitting?quotation?"Guardando...":"Creando...":quotation?"Guardar cambios":"Crear cotización"}</button></footer></form></div>;
};
