import type { Quotation } from "../../../types/quotation";
import { formatCurrency } from "../../../utils/formatCurrency";
import { formatDate, quotationStatusLabels, vehicleSummary } from "./quotationUtils";

export const QuotationList = ({ quotations, loading, onOpen }: { quotations: Quotation[]; loading: boolean; onOpen: (id: number) => void }) => {
  if (loading) return <p className="quotations-state" role="status">Cargando cotizaciones...</p>;
  if (!quotations.length) return <p className="quotations-state">No encontramos cotizaciones con esos filtros.</p>;
  return <><div className="quotations-table"><div className="quotations-table__head"><span>Número</span><span>Cliente / vehículo</span><span>Creada / vigencia</span><span>Total</span><span>Estado</span><span /></div>{quotations.map((quotation) => <article key={quotation.id}><strong>{quotation.quotation_number}</strong><div><span>{quotation.customer_name || "Venta mostrador"}</span><small>{vehicleSummary(quotation)}</small></div><div><span>{formatDate(quotation.created_at)}</span><small>Válida: {formatDate(quotation.valid_until)}</small></div><strong>{formatCurrency(quotation.total)}</strong><span className={`quotation-status quotation-status--${quotation.status}`}>{quotationStatusLabels[quotation.status]}</span><button type="button" onClick={() => onOpen(quotation.id)}>Ver</button></article>)}</div><div className="quotations-cards">{quotations.map((quotation) => <article key={quotation.id}><header><strong>{quotation.quotation_number}</strong><span className={`quotation-status quotation-status--${quotation.status}`}>{quotationStatusLabels[quotation.status]}</span></header><h3>{quotation.customer_name || "Venta mostrador"}</h3><p>{vehicleSummary(quotation)}</p><strong>{formatCurrency(quotation.total)}</strong><small>Creada {formatDate(quotation.created_at)} · Válida {formatDate(quotation.valid_until)}</small><button type="button" onClick={() => onOpen(quotation.id)}>Ver cotización</button></article>)}</div></>;
};
