import { useEffect, useRef, useState, type FormEvent } from "react";
import { createCustomer, createCustomerVehicle, getCustomer, getCustomers, getCustomerVehicles, updateCustomer, updateCustomerVehicle } from "../../../api/customers";
import type { Customer, CustomerPayload, CustomerVehicle, CustomerVehiclePayload, LaravelPaginator } from "../../../types/customer";
import { hasPermission } from "../../../utils/authStorage";
import { CustomerDetail } from "./CustomerDetail";
import { CustomerForm } from "./CustomerForm";
import { CustomerVehicleForm } from "./CustomerVehicleForm";
import "./AdminCustomersPage.css";

export const AdminCustomersPage = () => {
  const [customers, setCustomers] = useState<LaravelPaginator<Customer> | null>(null); const [searchInput, setSearchInput] = useState(""); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [selected, setSelected] = useState<Customer | null>(null); const [detailLoading, setDetailLoading] = useState(false); const [customerForm, setCustomerForm] = useState<"create" | "edit" | null>(null); const [vehicleForm, setVehicleForm] = useState<CustomerVehicle | "create" | null>(null); const requestId = useRef(0);
  const canView = hasPermission("customers.view");
  const load = async (page = 1, term = search) => { if (!canView) return; const id = ++requestId.current; setLoading(true); setError(""); try { const data = await getCustomers({ page, search: term, per_page: 15 }); if (id === requestId.current) setCustomers(data); } catch (cause) { if (id === requestId.current) setError(cause instanceof Error ? cause.message : "No se pudieron cargar los clientes."); } finally { if (id === requestId.current) setLoading(false); } };
  useEffect(() => { void load(1, ""); }, [canView]);
  const submitSearch = (event: FormEvent) => { event.preventDefault(); const term = searchInput.trim(); setSearch(term); void load(1, term); };
  const fetchCustomerDetail = async (id: number) => { const [customer, vehicles] = await Promise.all([getCustomer(id), getCustomerVehicles(id)]); return { ...customer, vehicles }; };
  const openCustomer = async (id: number) => { setDetailLoading(true); setError(""); try { setSelected(await fetchCustomerDetail(id)); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo cargar el cliente."); } finally { setDetailLoading(false); } };
  const refreshDetail = async () => { if (selected) setSelected(await fetchCustomerDetail(selected.id)); };
  const saveCustomer = async (payload: CustomerPayload) => { if (customerForm === "edit" && selected) { await updateCustomer(selected.id, payload); await refreshDetail(); } else { const created = await createCustomer(payload); await load(1, search); setSelected(await fetchCustomerDetail(created.id)); } setCustomerForm(null); };
  const saveVehicle = async (payload: CustomerVehiclePayload) => { if (!selected) return; if (vehicleForm !== "create" && vehicleForm) await updateCustomerVehicle(selected.id, vehicleForm.id, payload); else await createCustomerVehicle(selected.id, payload); await refreshDetail(); setVehicleForm(null); };
  if (!canView) return <section className="admin-customers"><div className="customers-empty"><h2>Acceso restringido</h2><p>No tienes permiso para consultar clientes.</p></div></section>;
  return <section className="admin-customers"><header className="admin-customers__header"><div><span>Relaciones comerciales</span><h2>Clientes</h2><p>Perfiles, vehículos e historial de compras en un solo lugar.</p></div>{hasPermission("customers.create") ? <button className="is-primary" type="button" onClick={() => setCustomerForm("create")}>Nuevo cliente</button> : null}</header>
    <form className="customers-search" onSubmit={submitSearch}><label className="customers-field"><span>Buscar cliente</span><input value={searchInput} onChange={(event) => setSearchInput(event.target.value)} placeholder="Nombre, teléfono, email o documento" /></label><button type="submit" disabled={loading}>{loading ? "Buscando..." : "Buscar"}</button>{search ? <button type="button" onClick={() => { setSearchInput(""); setSearch(""); void load(1, ""); }}>Limpiar</button> : null}</form>
    {error ? <p className="customers-error" role="alert">{error}</p> : null}
    {loading && !customers ? <div className="customers-empty">Clientes cargando...</div> : customers && !customers.data.length ? <div className="customers-empty">{search ? "No encontramos resultados." : "No hay clientes."}</div> : <div className="customers-list"><div className="customers-list__head"><span>Cliente</span><span>Contacto</span><span>Actividad</span><span>Estado</span><span /></div>{customers?.data.map((customer) => <article className="customers-list__row" key={customer.id}><div><strong>{customer.name}</strong><small>{customer.document || "Sin documento"}</small></div><div><span>{customer.phone || "Sin teléfono"}</span><small>{customer.email || "Sin email"}</small></div><div><span>{customer.vehicles_count ?? 0} vehículos</span><small>{customer.orders_count ?? 0} compras</small></div><span className={`customers-status ${customer.is_active ? "is-active" : "is-inactive"}`}>{customer.is_active ? "Activo" : "Inactivo"}</span><button type="button" onClick={() => void openCustomer(customer.id)}>Ver cliente</button></article>)}</div>}
    {customers && customers.last_page > 1 ? <nav className="customers-pager" aria-label="Paginación de clientes"><button type="button" disabled={loading || customers.current_page <= 1} onClick={() => void load(customers.current_page - 1)}>Anterior</button><span>Página {customers.current_page} de {customers.last_page}</span><button type="button" disabled={loading || customers.current_page >= customers.last_page} onClick={() => void load(customers.current_page + 1)}>Siguiente</button></nav> : null}
    <CustomerForm open={Boolean(customerForm)} customer={customerForm === "edit" ? selected : null} onClose={() => setCustomerForm(null)} onSave={saveCustomer} />
    <CustomerVehicleForm open={Boolean(vehicleForm)} vehicle={vehicleForm !== "create" ? vehicleForm : null} onClose={() => setVehicleForm(null)} onSave={saveVehicle} />
    <CustomerDetail customer={customerForm || vehicleForm ? null : selected} loading={!customerForm && !vehicleForm && detailLoading} onClose={() => setSelected(null)} onEdit={() => setCustomerForm("edit")} onAddVehicle={() => setVehicleForm("create")} onEditVehicle={setVehicleForm} />
  </section>;
};
