import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { CustomersApiError } from "../../../api/customers";
import { getVehicleBrands, getVehicleModels, getVehicleVersions } from "../../../api/vehicles";
import type { CustomerVehicle, CustomerVehiclePayload } from "../../../types/customer";
import type { VehicleBrand, VehicleModel, VehicleVersion } from "../../../types/vehicle";
import { useCustomerDialogFocus } from "./useCustomerDialogFocus";

type Props = { open: boolean; vehicle?: CustomerVehicle | null; onClose: () => void; onSave: (payload: CustomerVehiclePayload) => Promise<void> };
const blank = { brand: "", model: "", version: "", year: "", plate: "", vin: "", color: "", nickname: "", notes: "", is_active: true };

export const CustomerVehicleForm = ({ open, vehicle, onClose, onSave }: Props) => {
  const [form, setForm] = useState(blank); const [brands, setBrands] = useState<VehicleBrand[]>([]); const [models, setModels] = useState<VehicleModel[]>([]); const [versions, setVersions] = useState<VehicleVersion[]>([]); const [error, setError] = useState(""); const [errors, setErrors] = useState<Record<string, string[]>>({}); const [saving, setSaving] = useState(false); const lock = useRef(false);
  const close = () => { if (!lock.current) onClose(); }; const ref = useCustomerDialogFocus<HTMLDivElement>(open, close, !saving);
  const fieldError = (field: string) => errors[field]?.[0];
  const clearFieldError = (field: string) => setErrors((current) => { const next = { ...current }; delete next[field]; return next; });
  useEffect(() => { if (!open) return; Promise.all([getVehicleBrands(), getVehicleModels(), getVehicleVersions()]).then(([b,m,v]) => { setBrands(b); setModels(m); setVersions(v); }).catch((cause) => setError(cause instanceof Error ? cause.message : "No se cargó el catálogo vehicular.")); }, [open]);
  useEffect(() => { if (!open) return; setForm(vehicle ? { brand: String(vehicle.vehicle_brand_id ?? ""), model: String(vehicle.vehicle_model_id ?? ""), version: String(vehicle.vehicle_version_id ?? ""), year: String(vehicle.year ?? ""), plate: vehicle.plate ?? "", vin: vehicle.vin ?? "", color: vehicle.color ?? "", nickname: vehicle.nickname ?? "", notes: vehicle.notes ?? "", is_active: vehicle.is_active } : blank); setError(""); setErrors({}); }, [open, vehicle]);
  useEffect(() => { if (!open) return; const overflow = document.body.style.overflow; document.body.style.overflow = "hidden"; return () => { document.body.style.overflow = overflow; }; }, [open]);
  const visibleModels = models.filter((item) => String(item.vehicle_brand_id) === form.brand && item.is_active); const visibleVersions = versions.filter((item) => String(item.vehicle_model_id) === form.model && item.is_active); const selectedVersion = useMemo(() => versions.find((item) => String(item.id) === form.version), [form.version, versions]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (lock.current) return; lock.current = true; setSaving(true); setError(""); setErrors({}); const clean = (value: string) => value.trim() || null;
    try { await onSave({ vehicle_brand_id: form.brand ? Number(form.brand) : null, vehicle_model_id: form.model ? Number(form.model) : null, vehicle_version_id: form.version ? Number(form.version) : null, year: form.year ? Number(form.year) : null, plate: clean(form.plate.toUpperCase()), vin: clean(form.vin.toUpperCase()), color: clean(form.color), nickname: clean(form.nickname), notes: clean(form.notes), is_active: form.is_active }); }
    catch (cause) { if (cause instanceof CustomersApiError) { setErrors(cause.errors); const knownFields = ["vehicle_brand_id", "vehicle_model_id", "vehicle_version_id", "year", "plate", "vin", "color", "nickname", "notes", "is_active"]; const fields = Object.keys(cause.errors); setError(fields.length > 0 && fields.every((field) => knownFields.includes(field)) ? "" : cause.message); } else setError(cause instanceof Error ? cause.message : "No se pudo guardar el vehículo."); } finally { lock.current = false; setSaving(false); }
  };
  if (!open) return null;
  return <div ref={ref} className="customers-dialog" role="dialog" aria-modal="true" aria-labelledby="vehicle-form-title" tabIndex={-1}><button className="customers-dialog__backdrop" tabIndex={-1} type="button" disabled={saving} onClick={close} aria-label="Cerrar formulario" /><form className="customers-dialog__panel" onSubmit={submit}><header><div><span>Vehículo físico</span><h2 id="vehicle-form-title" tabIndex={-1} data-dialog-initial>{vehicle ? "Editar vehículo" : "Agregar vehículo"}</h2></div><button type="button" disabled={saving} onClick={close}>Cerrar</button></header><div className="customers-dialog__body"><div className="customers-form-grid">
    <label className="customers-field"><span>Marca</span><select value={form.brand} aria-invalid={Boolean(fieldError("vehicle_brand_id"))} onChange={(e) => { setForm((c) => ({ ...c, brand: e.target.value, model: "", version: "" })); clearFieldError("vehicle_brand_id"); }}><option value="">Sin especificar</option>{brands.filter((x) => x.is_active).map((x) => <option value={x.id} key={x.id}>{x.name}</option>)}</select>{fieldError("vehicle_brand_id") ? <small className="customers-field-error">{fieldError("vehicle_brand_id")}</small> : null}</label>
    <label className="customers-field"><span>Modelo</span><select value={form.model} disabled={!form.brand} aria-invalid={Boolean(fieldError("vehicle_model_id"))} onChange={(e) => { setForm((c) => ({ ...c, model: e.target.value, version: "" })); clearFieldError("vehicle_model_id"); }}><option value="">Sin especificar</option>{visibleModels.map((x) => <option value={x.id} key={x.id}>{x.name}</option>)}</select>{fieldError("vehicle_model_id") ? <small className="customers-field-error">{fieldError("vehicle_model_id")}</small> : null}</label>
    <label className="customers-field"><span>Versión</span><select value={form.version} disabled={!form.model} aria-invalid={Boolean(fieldError("vehicle_version_id"))} onChange={(e) => { setForm((c) => ({ ...c, version: e.target.value })); clearFieldError("vehicle_version_id"); }}><option value="">Sin especificar</option>{visibleVersions.map((x) => <option value={x.id} key={x.id}>{x.display_name}</option>)}</select>{fieldError("vehicle_version_id") ? <small className="customers-field-error">{fieldError("vehicle_version_id")}</small> : null}</label>
    <label className="customers-field"><span>Año</span><input type="number" min={selectedVersion?.year_from ?? 1900} max={selectedVersion?.year_to ?? new Date().getFullYear() + 2} value={form.year} aria-invalid={Boolean(fieldError("year"))} onChange={(e) => { setForm((c) => ({ ...c, year: e.target.value })); clearFieldError("year"); }} />{fieldError("year") ? <small className="customers-field-error">{fieldError("year")}</small> : selectedVersion ? <small>Rango: {selectedVersion.year_from}–{selectedVersion.year_to ?? "actual"}</small> : null}</label>
    {([['plate','Placa'],['vin','VIN'],['color','Color'],['nickname','Alias']] as const).map(([key,label]) => { const message = fieldError(key); return <label className="customers-field" key={key}><span>{label}</span><input value={form[key]} aria-invalid={Boolean(message)} onChange={(e) => { setForm((c) => ({ ...c, [key]: e.target.value })); clearFieldError(key); }} />{message ? <small className="customers-field-error">{message}</small> : null}</label>; })}
    <label className="customers-field customers-field--full"><span>Notas</span><textarea value={form.notes} aria-invalid={Boolean(fieldError("notes"))} onChange={(e) => { setForm((c) => ({ ...c, notes: e.target.value })); clearFieldError("notes"); }} />{fieldError("notes") ? <small className="customers-field-error">{fieldError("notes")}</small> : null}</label>{vehicle ? <label className="customers-toggle"><input type="checkbox" checked={form.is_active} onChange={(e) => { setForm((c) => ({ ...c, is_active: e.target.checked })); clearFieldError("is_active"); }} /> Vehículo activo{fieldError("is_active") ? <small className="customers-field-error">{fieldError("is_active")}</small> : null}</label> : null}</div>{error ? <p className="customers-error" role="alert">{error}</p> : null}</div><footer><button type="button" disabled={saving} onClick={close}>Cancelar</button><button className="is-primary" type="submit" disabled={saving}>{saving ? "Guardando..." : "Guardar vehículo"}</button></footer></form></div>;
};
