import { useEffect, useState } from "react";
import { getCustomerOrders, getCustomerVehicleOrders } from "../../../api/customers";
import type { Customer, CustomerVehicle, LaravelPaginator } from "../../../types/customer";
import type { Order } from "../../../types/order";
import { formatCurrency } from "../../../utils/formatCurrency";
import { hasPermission } from "../../../utils/authStorage";
import { formatOrderDate, orderStatusLabels, paymentStatusLabels } from "../orders/orderUtils";
import { useCustomerDialogFocus } from "./useCustomerDialogFocus";

type Props = { customer: Customer | null; loading: boolean; onClose: () => void; onEdit: () => void; onAddVehicle: () => void; onEditVehicle: (vehicle: CustomerVehicle) => void };
const vehicleBrand = (v: CustomerVehicle) => v.vehicle_brand ?? v.vehicleBrand;
const vehicleModel = (v: CustomerVehicle) => v.vehicle_model ?? v.vehicleModel;
const vehicleVersion = (v: CustomerVehicle) => v.vehicle_version ?? v.vehicleVersion;

const Pager = ({ page, onPage }: { page: LaravelPaginator<unknown>; onPage: (value: number) => void }) => <nav className="customers-pager" aria-label="Paginación"><button type="button" disabled={page.current_page <= 1} onClick={() => onPage(page.current_page - 1)}>Anterior</button><span>Página {page.current_page} de {page.last_page}</span><button type="button" disabled={page.current_page >= page.last_page} onClick={() => onPage(page.current_page + 1)}>Siguiente</button></nav>;
const History = ({ data }: { data: LaravelPaginator<Order> | null }) => !data ? <p>Cargando compras...</p> : !data.data.length ? <p>Este registro todavía no tiene compras asociadas.</p> : <div className="customer-history">{data.data.map((order) => <article key={order.id}><div><strong>#{order.order_number}</strong><span>{formatOrderDate(order.created_at)}</span></div><div><strong>{formatCurrency(order.total)}</strong><span>{orderStatusLabels[order.status]} · {paymentStatusLabels[order.payment_status]}</span><small>{order.items?.length ?? 0} líneas comerciales</small></div><a href={`/crm/orders`}>Ver en Órdenes</a></article>)}</div>;

export const CustomerDetail = ({ customer, loading, onClose, onEdit, onAddVehicle, onEditVehicle }: Props) => {
  const [orders, setOrders] = useState<LaravelPaginator<Order> | null>(null); const [vehicleHistory, setVehicleHistory] = useState<{ vehicle: CustomerVehicle; page: LaravelPaginator<Order> | null } | null>(null); const [error, setError] = useState("");
  const open = Boolean(customer || loading); const ref = useCustomerDialogFocus<HTMLDivElement>(open, onClose);
  useEffect(() => { if (!customer) return; setOrders(null); getCustomerOrders(customer.id).then(setOrders).catch((cause) => setError(cause instanceof Error ? cause.message : "No se cargó el historial.")); }, [customer]);
  useEffect(() => { if (!open) return; const overflow = document.body.style.overflow; document.body.style.overflow = "hidden"; return () => { document.body.style.overflow = overflow; }; }, [open]);
  const loadOrders = (page: number) => { if (customer) getCustomerOrders(customer.id, page).then(setOrders).catch((cause) => setError(cause instanceof Error ? cause.message : "No se cargó el historial.")); };
  const openVehicleHistory = (vehicle: CustomerVehicle, page = 1) => { if (!customer) return; setVehicleHistory({ vehicle, page: null }); getCustomerVehicleOrders(customer.id, vehicle.id, page).then((result) => setVehicleHistory({ vehicle, page: result })).catch((cause) => setError(cause instanceof Error ? cause.message : "No se cargó el historial del vehículo.")); };
  if (!open) return null;
  return <div ref={ref} className="customers-dialog" role="dialog" aria-modal="true" aria-labelledby="customer-detail-title" tabIndex={-1}><button className="customers-dialog__backdrop" tabIndex={-1} type="button" onClick={onClose} aria-label="Cerrar detalle" /><section className="customers-dialog__panel customers-detail">{loading || !customer ? <p className="customers-empty" data-dialog-initial tabIndex={-1}>Cargando cliente...</p> : <><header><div><span>Perfil comercial</span><h2 id="customer-detail-title" data-dialog-initial tabIndex={-1}>{customer.name}</h2><p><span className={`customers-status ${customer.is_active ? "is-active" : "is-inactive"}`}>{customer.is_active ? "Activo" : "Inactivo"}</span></p></div><div>{hasPermission("customers.update") ? <button type="button" onClick={onEdit}>Editar</button> : null}<button type="button" onClick={onClose}>Cerrar</button></div></header><div className="customers-dialog__body">
    <section className="customer-section"><h3>Información</h3><div className="customer-info"><div><span>Teléfono</span><strong>{customer.phone ?? "No registrado"}</strong>{customer.phone ? <div><a href={`tel:${customer.phone}`}>Llamar</a><a href={`https://wa.me/${customer.phone.replace(/\D/g, "")}`} target="_blank" rel="noreferrer">WhatsApp</a></div> : null}</div><div><span>Email</span><strong>{customer.email ?? "No registrado"}</strong>{customer.email ? <a href={`mailto:${customer.email}`}>Email</a> : null}</div><div><span>Documento</span><strong>{customer.document ?? "No registrado"}</strong></div><div><span>Ubicación</span><strong>{[customer.city, customer.address].filter(Boolean).join(" · ") || "No registrada"}</strong></div></div>{customer.notes ? <p>{customer.notes}</p> : null}</section>
    <section className="customer-section"><header className="customer-section__header"><div><h3>Vehículos</h3><p>{customer.vehicles?.length ? `${customer.vehicles.length} registrados` : "Este cliente todavía no tiene vehículos."}</p></div>{hasPermission("customers.create") ? <button type="button" onClick={onAddVehicle}>Agregar vehículo</button> : null}</header><div className="customer-vehicles">{customer.vehicles?.map((vehicle) => { const brand = vehicleBrand(vehicle); const model = vehicleModel(vehicle); const version = vehicleVersion(vehicle); return <article key={vehicle.id}><div><span>{vehicle.nickname || "Vehículo"}</span><h4>{[brand?.name, model?.name].filter(Boolean).join(" ") || "Vehículo sin catálogo"}</h4><p>{[version?.display_name, vehicle.year].filter(Boolean).join(" · ") || "Datos parciales"}</p></div><dl><div><dt>Placa</dt><dd>{vehicle.plate ?? "—"}</dd></div><div><dt>Color</dt><dd>{vehicle.color ?? "—"}</dd></div></dl><span className={`customers-status ${vehicle.is_active ? "is-active" : "is-inactive"}`}>{vehicle.is_active ? "Activo" : "Inactivo"}</span><div className="customer-card-actions"><button type="button" onClick={() => openVehicleHistory(vehicle)}>Ver compras</button>{hasPermission("customers.update") ? <button type="button" onClick={() => onEditVehicle(vehicle)}>Editar</button> : null}</div></article>; })}</div></section>
    {vehicleHistory ? <section className="customer-section"><header className="customer-section__header"><div><h3>Historial del vehículo</h3><p>{vehicleHistory.vehicle.nickname || vehicleHistory.vehicle.plate || "Vehículo seleccionado"}</p></div><button type="button" onClick={() => setVehicleHistory(null)}>Cerrar historial</button></header><History data={vehicleHistory.page} />{vehicleHistory.page ? <Pager page={vehicleHistory.page} onPage={(page) => openVehicleHistory(vehicleHistory.vehicle, page)} /> : null}</section> : null}
    <section className="customer-section"><h3>Historial de compras</h3><History data={orders} />{orders ? <Pager page={orders} onPage={loadOrders} /> : null}</section>{error ? <p className="customers-error" role="alert">{error}</p> : null}</div></>}</section></div>;
};
